### ISSUE TITLE
External identifiers should be nested within objects and not referenced

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#102]
Even though we're using a Venetian Blind design in our XSD, the ExternalIdentifer objects are effectively simple elements which should be defined within the object for which they provide an alternative ID, not defined in a big list elsewhere and referenced via xs:IDREF.

**Comment by cjerdonek** [comment]
I just wanted to carry over my point from before that I think the type we define and use should be `ExternalIdentiferCollection`, since we always support adding multiple identifiers.

**Comment by cjerdonek** [comment]
I created PR #108 to address this.

**Comment by cjerdonek** [comment]
Question: is there already a proposal for how to allow external identifiers to be provided for objects in the feed via flat files?

**Comment by cjerdonek** [comment]
@jdmgoogle I think this can be closed now, except for the issue of how external identifiers would be handled for all objects in the flat files (see also issue #109).  Should we open a separate issue for that, or work that out here?

**Comment by jdmgoogle** [comment]
@cjerdonek I think we can close this one out since the flat file discussion seems to be happening in #109.
