### ISSUE TITLE
Implement Venetian Blind

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#113]
Implement Venetian Blind per our style guide [here](https://github.com/votinginfoproject/vip-specification/blob/vip5/STYLEGUIDE.md#type-definitions-global-vs-local).

**Comment by jungshadow** [comment]
@cjerdonek Do you happen to know who's responsible for this? Feel free to assign, if you do.

**Comment by cjerdonek** [comment]
@jdmgoogle and @pstenbjorn IIRC.

**Comment by pstenbjorn** [comment]
@cjerdonek @jungshadow and @jdmgoogle - I will have time after tomorrow to lay out the proposed realignment of the standard using this style.  I would also like to have a reference XML document included with this.

**Comment by jdmgoogle** [comment]
Based on @pstenbjorn's comment in #136, I'm assuming this can be closed. Reopen if I misread/misinterpreted his comments.

**Comment by pstenbjorn** [comment]
@jdmgoogle thank you
