### ISSUE TITLE
Style: should type names end in "Type"?

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#116]
I noticed that some type names end in "Type" (e.g. "ContestType" and "DetailAddressType"), but there doesn't seem to be a pattern as to which ones do.  For types like those, the suffix seems redundant to me.  Also, if such types end in "Type," it seems like they all should.

Personally, I think suffixes like "Type" and "Status" should be reserved for enumerations like "BallotMeasureType" and "CandidatePreElectionStatus," because they enumerate type _names_ (and not simply because they are the name of a type).  I think the style guide should clarify this and remove the ambiguity as to when the suffix should be present.

**Comment by jdmgoogle** [comment]
I generally agree with this. The current naming also uses the FooType naming scheme when referring to abstract base classes which can never be instantiated. I'm okay with the FooType naming being used there, too.

**Comment by cjerdonek** [comment]
If we go with a convention for abstract base classes, I'd prefer something distinct that we don't also use for some concrete classes.  In other words, if we use "FooType" for abstract base classes, I think Type should be disallowed for others (e.g. the BallotMeasureType enum of ballot-measure, initiative, referendum, etc).  Another option is to choose a different convention for abstract base classes like "FooBase".

**Comment by jdmgoogle** [comment]
I'm okay with pure-abstract classes being renamed to "FooBase".

**Comment by cjerdonek** [comment]
I created PR #121 for this.

**Comment by cjerdonek** [comment]
Closed by PR #121.
