### ISSUE TITLE
Identify and adopt a uniform address standard

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#118]
Currently we use two main address formats: the simple multi-string "AddressLine" in the Contact object, and a more detailed lines/city/state/zip format in SimpleAddressType. The reason for this is that the Contact object comes from 1622.2, and we (Google) hope to promote 1622.2 as a data standard for international election results reporting, including in jurisdictions where the city/state/zip address format doesn't work. The VIP address elements, though, are used for creating street segments in a very US-centric format; the simplicity of the use case is actually what helped spur adoption, and we don't want to deviate from those roots.

This is a placeholder issue to remind us to locate and evaluate different address standards which could be used in both VIP and the IEEE VSSC efforts.

Cc @johnpwack @kennethmbennett @pstenbjorn since they have previously expressed interest in tackling this (non-trivial) problem.

**Comment by cjerdonek** [comment]
> Currently we use two main address formats: the simple multi-string "AddressLine" in the Contact object, and a more detailed lines/city/state/zip format in SimpleAddressType.

FYI, there are actually three address formats currently being used in VIP:

1. the generic "AddressLines" approach used in the Contact object (from 1622.2, for things like Office addresses),
2. "SimpleAddressType" (used for the address of PollingLocations), which breaks out City / State / Zip, and
3. the even more structured "DetailAddressType" (used in StreetSegment), which also breaks out things like HouseNumberPrefix, HouseNumberSuffix, StreetSuffix, etc.

**Comment by jdmgoogle** [comment]
Circling back to this. To update @cjerdonek's comment from earlier, the current address schemes uses in VIP 5.0 are:

1. the generic `AddressLines` elements in `PollingLocation` and `ContactInformation` (the latter of which is used in the NIST format); and
2. the `StreetSegment` object, which is basically nothing but an address now.

**Comment by jdmgoogle** [comment]
For various reasons progress on 5.1 has slipped (I basically ran out of time in December to work on it). In order to not make big changes leading up to the 2016 election, I'm going to push this back to the 5.2 milestone.

**Comment by afsmythe** [comment]
Pushing this to 5.3 (post 2020 elections) milestone.

**Comment by afsmythe** [comment]
We've reintroduced `SimpleAddressType` to `PollingLocation` as of the 5.2 release, and I believe the consensus is that this was a good move. 5.2 also saw an expansion of the `StreetSegment` object with `HouseNumberPrefix` and `HouseNumberSuffix` but we're no longer using the `DetailAddressType` mentioned in https://github.com/votinginfoproject/vip-specification/issues/118#issuecomment-94833163

I believe the `AddressLine` fields for implementation of `ContactInformation` is sufficient, but if there are cases where a structured address (via `SimpleAddressType`) would meaningfully improve usability (geocoding) of `ContactInformation` addresses then those should be identified here. 

Is there a still a requirement to identify a uniform address standard which moves away from `SimpleAddressType`? Can we close this issue?

**Comment by JDziurlaj** [comment]
My suggestion is do not let consensus on finding a standard stop you from solving current pain points. We have been working with the FGDC specification in NIST 1500-102 (VRI). We may reevaluate that at some point due to bugs in the FGDC schema that have not been fixed over several years.

**Comment by jswiesner** [comment]
SimpleAddressType has proven more reliable and easier to make use of relative to AddressLines. We have consistently seen a higher geocoding success rate with SimpleAddressType versus AddressLines addresses. Considering the US-specific nature of the VIP spec, I support favoring the use of SimpleAddressType as much as possible in the spec. Closing this issue sounds good to me.

**Comment by jdmgoogle** [comment]
I think SimpleAddressType handles common cases much better than AddressLine, but AddressLine handles cases where reality doesn't cleanly map to a SimpleAddressType. So IMO we should encourage SAT use where possible, but I'd be nervous about removing AddressLine altogether.

**Comment by afsmythe** [comment]
Thanks! I believe we're in agreement to close this.
