### ISSUE TITLE
Style: line length

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#126]
I wanted to suggest some sort of non-strict line length guideline to apply to all of our files (xml, html, md).  The main reason is to make diffs more useful (e.g. those that appear in GitHub).  I noticed that some lines in the HTML and markdown seem to run very long (e.g. 200+ characters).  Maybe it could be phrased as a goal of 80 characters, but longer is fine whenever it aids readability.

**Comment by cjerdonek** [comment]
This wouldn't apply to sample feeds, of course (e.g. XML and CSV).

**Comment by jdmgoogle** [comment]
Given the verbosity of XML and HTML, I propose a 100-character suggested line limit. The current HEAD for vip5 has a vip_spec.xml of 662 lines. Of those:

- 111 are 81+ characters long; and
- 22 are 100+ characters long.

**Comment by cjerdonek** [comment]
100 as the suggestion seems fine to me.  I can write up the PR.

**Comment by cjerdonek** [comment]
Created PR #128 for this.

**Comment by cjerdonek** [comment]
Closed by PR #128.
