### ISSUE TITLE
Order type definitions in XSD

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#136]
We need to order the type definitions in the XSD per the style guide.  Is it okay for me to do this, or is someone else already working on a big change to the XSD?

**Comment by jdmgoogle** [comment]
Not sure what the status is of @pstenbjorn's Venetian-Blind-izing the XSD.

**Comment by pstenbjorn** [comment]
@cjerdonek @jdmgoogle Venetian Blinding is merged.  I am fine with @cjerdonek ordering the XSD.

**Comment by cjerdonek** [comment]
I will create a PR now.

**Comment by cjerdonek** [comment]
Started PR #137.

**Comment by jdmgoogle** [comment]
Since this should be a relatively non-controversial set of PRs (i.e., just sorting some elements and attributes), would @jungshadow or @pstenbjorn object if we waived the normal two-reviewer rule and I reviewed @cjerdonek's PRs by myself?

**Comment by jungshadow** [comment]
Fine by me.

**Comment by pstenbjorn** [comment]
Same here

**Comment by cjerdonek** [comment]
Closed by PR #137.
