### ISSUE TITLE
Address remaining local and global types

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#142]
I noticed that OrderedContest should be in-lined inside the BallotStyle definition.  Also, State needs to be made a named type rather than anonymous.

**Comment by jdmgoogle** [comment]
I'm not sure that OrderedContest needs to be inlined.
The elements within each object need to be sorted.
Also ContactInformation should be inlined.
I'm running out of steam right now, though, so let's pick up this last cleanup on Monday.

**Comment by cjerdonek** [comment]
Also, the Term object should be in-lined inside Office.

**Comment by cjerdonek** [comment]
Yeah, I'm just making a note for Monday, etc.  OrderedContest is used only within BallotStyle and doesn't have an ID attribute (and doesn't fit any of the criteria in the style guide), which is why it should be in-lined.

**Comment by cjerdonek** [comment]
On second thought, I will start a PR for this.

**Comment by cjerdonek** [comment]
Created PR #143.

Regarding ContactInformation, I checked, and I don't think it can/should be in-lined because it is used/referenced in more than one type: Person, Source, Department, Department.VoterService, and Office.
