### ISSUE TITLE
style guide: document "identifier" pattern for in-lined objects

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#149]
I think it would be worth adding a note about our pattern of adding an optional "identifier" attribute with type string for objects whose data is in-lined and that do not have an ID.  When flat files are used, the identifier can be used in lieu of an ID to link the data back to the row of the flat file it came from.

**Comment by jdmgoogle** [comment]
Go for it. All yours. :)

**Comment by cjerdonek** [comment]
Will do, maybe not today but within the next few days. :)

**Comment by cjerdonek** [comment]
Closed by PR #229.
