### ISSUE TITLE
Sample feed missing StreetSegment elements

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#151]
I completely missed this in my review, so *mea culpa*. Since they're pretty key to this whole operation, there should be a few `StreetSegment` elements in the sample feed.

**Comment by pstenbjorn** [comment]
@jungshadow i can take on the sample feed with the latest schema changes as i would like to test using existing csv to create.

**Comment by jungshadow** [comment]
No objections here, but I will say that I do like the fact that it's small enough to browse on GitHub without going to the raw source. It's super-great if you can get it to work with the existing CSVs (I'm pretty sure @pkoms and @nomadaisy will be overjoyed), but whatever gets posted here I think should be a small sample of that data.

What say you, @jdmgoogle?

**Comment by jdmgoogle** [comment]
We should probably update the sample feed to include a few common use cases, including (but not limited to):

1. Ballot rotation;
2. Basic street segments;
3. Street segments with unit numbers;
4. A multi-candidate contest (e.g., President and Vice President); and
5. One person running for multiple offices (e.g., a Senator running both for President and their current seat).

Are there any other use cases we might want to demonstrate?

**Comment by pstenbjorn** [comment]
@jdmgoogle one of the use cases that I am interested in representing is the use of the `Precinct` element to represent both splits and precincts.  
The other use cases that I can think of are
1.) Early voting sites
2.) Vote by mail election
3.) Judicial retention elections

As I work through the sample feed I am sure I will have other thoughts.

**Comment by jungshadow** [comment]
Should we open up issues for the other use cases?
