### ISSUE TITLE
Fix remaining todos on ballot_measure_contest.rst

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#158]
Two things here for discussion:

* Should `BallotMeasureContest.Type` be required?
* Is `BallotMeasureContest.FullText` a required field?

To the latter bullet point, there were a number of places in the generated doc files where some of the required fields were optional. In [the 3.0 docs](http://votinginfoproject.github.io/vip-specification/#referendumitems), `referendum.title` and `referendum.text` were both required fields. While the similar elements from 3.0 and 5.0 aren't exactly carbon copies, just wanted to make sure it was deliberate. /cc @cjerdonek @jdmgoogle @pstenbjorn

**Comment by jdmgoogle** [comment]
> To the latter bullet point, there were a number of places in the generated doc files where some of the required fields were optional.

That may have been a bug in my code. I can go double-check if you'd like, or we can just assume that I messed up the code. :)

As for the question of required versus optional, I feel that

1. `BallotMeasureContest.Type` should be optional since it's there if an election officially really needs to distinguish between two different types of ballot measures in a single election.
2. I think `BallotMeasureContest.FullText` should be optional. I know in CA they can run for pages and pages.

**Comment by jungshadow** [comment]
> That may have been a bug in my code. I can go double-check if you'd like, or we can just assume that I messed up the code. :)

Heh...that code was huge for saving me a ton of time creating reST tables, which, I believe, is a form of punishment in violation of the UN Convention Against Torture.

> As for the question of required versus optional, I feel that
>
>   1. BallotMeasureContest.Type should be optional since it's there if an election officially really needs to distinguish between two different types of ballot measures in a single election.
>   2. I think BallotMeasureContest.FullText should be optional. I know in CA they can run for pages and pages.

Sounds good to me.

**Comment by jungshadow** [comment]
@jdmgoogle In the interest of keeping discussions in the issues rather than the PRs, regarding [your comment](https://github.com/votinginfoproject/vip-specification/pull/172#issuecomment-105492034) on `PassageThreshold`, if one `BallotMeasureContest` is dependent on another `BallotMeasureContest` to pass, should there be a link between the two? Not that I'm advocating for it–or that it's even possible to connect the two in the existing election systems–but a textual connection (i.e. referencing the title of the opposing ballot measure in the `PassageThreshold`) is fairly limiting.

Dunno...thoughts?
