### ISSUE TITLE
Contests allow multiple values for every field

### ISSUE THREAD

**Issue by jmwaura** [votinginfoproject/vip-specification#16]
There seems to be a bug in the `contestType` schema in vip_spec_pending.xsd:

    <xs:complexType name="contestType">
      <xs:choice maxOccurs="unbounded">
        <xs:element name="election_id" type="xs:string" maxOccurs="1"/>
        <xs:element name="electoral_district_id" type="xs:string"/>
        ...
        <xs:element name="candidate" type="candidateType" minOccurs="0"/>
        <xs:element name="referendum" type="referendumType" minOccurs="0"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>

If I'm reading this right, this allows an unbounded number of any of the fields specified in the choice element (including those that have an explicit maxOccurs=1)

Is it possible `<xs:choice maxOccurs="unbounded">` was intended to be `<xs:sequence>`? In this case, I believe the bounds on some of the fields will need to be updated. `candidate` for instance should be allowed to occur more than once.

**Comment by jdmgoogle** [comment]
If we decide to use 1622.2-isms for ballot information this will end up being obsolete. Otherwise I agree with jmwaura's report.

**Comment by jdmgoogle** [comment]
We've completely revamped the ballot info so this is obsolete. Closing.
