### ISSUE TITLE
If RetentionContest exists, is BallotMeasureType "retention" necessary?

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#160]
I may have missed something in the discussion on this, but we have an element `RetentionContest` and a `BallotMeasureType` value of "retention." If we have the element, do we need the value for a `BallotMeasureContest`? Let me know if I'm crazy here.

**Comment by jdmgoogle** [comment]
I don't believe so. I'm readying a PR to make a few very minor fixes, and this will be one of them.

**Comment by jdmgoogle** [comment]
Fixed by #161.
