### ISSUE TITLE
Include a way to specify campaign committee IDs

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#164]
Our first comment from our state partners:

> One additional thing we do for candidates on the state and national level is to include campaign committee IDs. We use these committee IDs to link the candidate to our campaign finance reporting data.

I know that `ExternalIdentifiers` can handle just about anything, but does "national-level" for a type have enough specificity for campaign committee IDs? More generally, if one feed has multiple "national-level" identifiers on an element, will that end up being ambiguous for folks processing the data (i.e. does "national-level" really tell you more than "other")?

**Comment by jdmgoogle** [comment]
This is *exactly* the use case for `ExternalIdentifiers`. Just use `Type` of "other", `OtherType` of "campaign-committee-id", and `Value` of whatever the ID is.

**Comment by jungshadow** [comment]
Fair point (forgot about `OtherType` for a moment there). I'm still thinking about the effectiveness of "national-level," tho...

Assuming no one has issues with this approach, I'll mark this as resolved and close.

**Comment by jdmgoogle** [comment]
Tagging this one as closed. Re-open as necessary.
