### ISSUE TITLE
Update street segments to handle addresses which are intersections

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#166]
This is an extension of #118, specifically in how we can apply it to the `StreetSegment` element.

**Comment by jdmgoogle** [comment]
Pinging @jktomer because we need to review the number and quantity of non-numeric addresses we've encountered.

Paging @kennethmbennett because LA County probably has a number of these in their jurisdiction, and we need to better understand their needs.

**Comment by Josh-LACRRCC** [comment]
Here are some LA County examples of edge-case addresses.

Full prefix/suffix address that might conflict with other localities street naming conventions:
"2317 West Garvey Ave N, West Covina, CA 91790" Which is not synonymous with an "Avenue N" style of street name.

Address with no start/end house numbers (zero's):
Marina addresses where the street name = slip # / berth #
"SLIP G-19, Marina Del Rey, CA 90292"
"Berth 100, San Pedro, CA 90731"

and Intersection address
"Washington & Lake, Pasadena, CA 91104"

We have about a thousand Street Segments with 'zero' house numbers, with at least a few hundred registered voters. @kennethmbennett would need to provide input about their actual implementation.

**Comment by jdmgoogle** [comment]
@Josh-LACRRCC Thanks.

1. I think the full prefix/suffix might work as-is, and our geocoder would be fine with it. I'll have to test some addresses, though.

2. Addresses with no house numbers would probably be supported (at least spec-wise) by using the `IncludesAllAddresses` flag in a street segment. We'd just have to make sure we process it on our end. That may be non-trivial, though; your thoughts, @jktomer?

3. I don't know how we'd handle intersections. How many voters fall into this category?

**Comment by jdmgoogle** [comment]
Picking this back up.

1. The full prefix/suffix did work as-is, and our geocoder worked with your example.

2. I recommend trying to support these using an `IncludesAllAddresses` flag. Some will work (e.g., the Berth appears to geocode) and some will not (the SLIP address did not).

3. Support for intersections as an address we can link to a precinct will not happen in 5.1, and may be a stretch for 5.2.

**Comment by jdmgoogle** [comment]
Given that issue (1) currently works, issue (2) can be covered with an existing feature, and (3) will not happen for 5.1, I'm renaming this to reflect the specific feature (i.e., support for addresses which are intersections) and moving it to the 5.2 milestone.

**Comment by afsmythe** [comment]
Moving this 5.3 and making a note that VIP is hoping to improve coverage of tribal and indigenous lands. Maybe there's some application of this review to that end?

**Comment by jdmgoogle** [comment]
SGTM

**Comment by afsmythe** [comment]
With the momentum of increased geocoding by elections offices, would this requirement be better served by the inclusion of a `LatLng` field to `StreetSegment` (or a more vector type of spatial data object) in lieu of introducing a "cross street" type of attribute?

**Comment by jswiesner** [comment]
A LatLng for street segments would actually be useful for QA purposes, but at best only slightly helpful for handling intersections.

I'm curious about cases like "Washington & Lake, Pasadena, CA 91104". Is the expectation that the voter would query for their voting information with an address in that form that as well? For street segments to serve their purpose, we need the address as represented in the street segment to align with the way the voter would query for their voting information.

To illustrate an example where this would break down, imagine a voter that lives at that intersection but from experience knows that address search tools tend to struggle with "Washington & Lake". The voter knows that the intersection is roughly equal to "1340 Lake Ave, Pasadena, CA", so they opt to provide this closest street address when looking up their voting information. If that occurs, then it doesn't matter how well the intersection is modeled as a street segment, we would likely fail to map the user query to the segment.

Another consideration is that the longer term shift towards geospatial data may provide the solution to this problem. One possibility is that we just defer improved handling of intersections to when we support geospatial boundaries for precincts. In that case, it's just a matter of figuring out which precinct the intersection is contained within (much easier!).

**Comment by jswiesner** [comment]
I propose we close this issue in favor of geospatial modeling of precincts, which will be available from 6.0. If a state or locality has a large number of these types of addresses to support, this would provide a strong motivation to instead model the precinct boundary with a polygon as opposed to street segments. Thoughts?

**Comment by jdmgoogle** [comment]
@afsmythe Do we have a sense of how many states want to do intersections but won't be doing GIS anytime soon?

**Comment by afsmythe** [comment]
Not at this time.. the complication is as @jswiesner says, that we have to model the `StreetSegment` with how a person would search for it. Because of the various ways an intersection can be typed in, it seems the only sustainable way of supporting this for the user would be to support a "drop pin on map" functionality to identify their registered address. With that aim in mind, it is either a "point in polygon" check of the placed pin and the precinct shape or some sort of a fuzzy match of the pin placement and nearby geocoding data tied to a `StreetSegment`, e.g. `StreetSegment.LatLng`. 

This is an old issue. I think cross streets for `PollingLocation` somewhat present in states like Pennsylvania, but cross streets for `StreetSegment` seems less common. 

Noting that the existing `StreetSegment.IncludesAllAddresses` field seems like it _could_ support intersections. I'd like to see this field tested collaboratively because I don't recall if it's been proven to work.

**Comment by jswiesner** [comment]
I could foresee `StreetSegment.IncludesAllAddresses` working in some cases where the entire street that contains the intersection maps to the same precinct. But I don't think it would solve this issue for all cases. 

If we don't have any indication that this is a pressing issue for states, and we expect the shift away from StreetSegments towards geospatial data will better solve the problem, I suggest we either move this to a 6.1 milestone (the next, next release) to reevaluate in the future, or just close the issue. @afsmythe @jdmgoogle WDYT?

**Comment by afsmythe** [comment]
I'm in favor of closing this.

**Comment by jswiesner** [comment]
Closing sounds good to me. @jdmgoogle are you in agreement to close this?
