### ISSUE TITLE
How to best handle presentation logic in long text areas

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#170]
For elements like `BallotMeasureContest`, there are fields that can contain multiple paragraphs of text (e.g. `FullText`) and need to allow for some markup of some kind. A few states provide the information as HTML, but that tends to be troublesome for processing. Should there be a standard/enforced way of providing this formatted data or should everything be wrapped in a CDATA section?

**Comment by pstenbjorn** [comment]
@jungshadow there are essentially two choices for formatted data, replace special characters and handle escape codes e.g. `&lt;div id=&quot;header&quot;&gt;` or use CDATA to wrap the formatted block e.g. `<![CDATA[<div id="header">]]>`.  I am agnostic since both would need handling on the generation side and neither is perfect.

**Comment by jdmgoogle** [comment]
I agree with @pstenbjorn that this should be up to the data providers on how to handle.

**Comment by cjerdonek** [comment]
Regarding the underlying data itself (and not how it should be encoded), I do agree that formatted text seems necessary in some cases.  For example, if the full text contains strikeouts as underlines, there would need to be a way to support that (e.g. HTML or some other kind of markup language).

A couple comments:

1. @jungshadow, are you saying that is HTML problematic as a data source, independent of presentation?  Or were you simply saying that it needs to be thought through.
2. If we are going to allow more than one type of formatting, for example HTML as one possibility and plain-text as another (e.g. which would preserve end-of-lines, unlike HTML), then it seems like there would need to be a way to annotate the element with the name of the formatting that is being provided.  For example, there could be some kind of "format_type" attribute that accepts values from an enum with values like "plain" and "html".

**Comment by jungshadow** [comment]
Answering these comments in reverse order:

> @jungshadow, are you saying that HTML is inherently problematic as a data source, independent of how it is encoded? Or were you simply saying that the way it is encoded requires additional thought?

@cjerdonek More the latter and was digging for some opinions. We've seen some standard (X)HTML and some non-standard HTML. The presentation logic can wreak havoc with tools, since developers will never know what they're going to get. Additionally, the jurisdictions will use CSS classes to display bits of information a certain way, but then is only applicable to their site. I understand that we can't do anything about a few of these cases, but I figure it's worth discussing.

> If we are going to allow more than one type of formatting, for example HTML as one possibility and plain-text as another (e.g. which would preserve end-of-lines, unlike HTML), then it seems like there would need to be a way to annotate the element with the name of the formatting style that is being provided. For example, there could be some kind of "format_type" attribute that accepts values from an enum with values like "plain" and "html".

I'll ruminate on that for a bit. I think you're probably right, but we've only been exposed to this data on a small scale and I'm wondering if we just wait until we see more before trying to enumerate the various type.

> @jungshadow there are essentially two choices for formatted data, replace special characters and handle escape codes e.g. &lt;div id=&quot;header&quot;&gt; or use CDATA to wrap the formatted block e.g. <![CDATA[<div id="header">]]>. I am agnostic since both would need handling on the generation side and neither is perfect.

We do the former, now, but we've had to tweak the data to bend to the tools or tweak the tools to bend to the data. Neither option has been great and the variability in the quality of the HTML has been trying. I'm thinking of app developers (and, selfishly, us) in trying to come up with a best practice for this data and a validation rule to go around it.

**Comment by jdmgoogle** [comment]
Decision: everything is going to be plain text, with standard XML escaping for special characters.

States that send HTML to Pew/other VIP-feed-generators will have that HTML converted to text before the feed is published.

**Comment by jungshadow** [comment]
Just thought about this issue a bit more and couldn't we do (roughly) something like this?

```xml
<xs:simpleType name="PreformattedText">
  <xs:restriction base="xs:string">
    <xs:whitespace value="preserve" />
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="LanguageString">
  <xs:simpleContent>
    <xs:extension base="PreformattedText">
      <xs:attribute name="language" type="xs:language" use="required" />
    </xs:extension>
  </xs:simpleContent>
</xs:complexType>
```
Theoretically, this would preserve the whitespace (i.e. newlines and all) in the `InternationalizedText.Text` blocks...assuming I haven't screwed this up. I'm going to look to @pstenbjorn, @jdmgoogle, @cjerdonek, and @nomadaisy to explain why this won't work, since my XML-fu isn't all that strong :)

**Comment by cjerdonek** [comment]
I didn't research this carefully, but my understanding is that "xs:string" already preserves whitespace (i.e. it's just a string of characters), so it doesn't seem to me like we need to take any action.  It's HTML that collapses whitespace, etc, but we aren't going with HTML.

**Comment by cjerdonek** [comment]
Here is one reference: http://books.xmlschemata.org/relaxng/ch19-77303.html

> **Description**
> The lexical and value spaces of xsd:string are the set of all possible strings composed of any character allowed in a XML 1.0 document without any treatment done on whitespace.
> **Restrictions**
> This is the only datatype that leaves all the whitespace. When whitespace isn't significant, xsd:token is preferred.

**Comment by jungshadow** [comment]
@cjerdonek Gotcha. I was imagining this would provide explicit instructions for the processor, but, looking a bit deeper, you're right, it does look like it's supposed to be preserved. On the HTML-side of things, I suppose we could dump certain responses into `<pre>`-blocks...but that might be asking for trouble.

**Comment by cjerdonek** [comment]
Yeah, that's another option.  If we had decided to go with HTML as the standard, then jurisdictions equipped only for plain-text could just enclose in `<pre>` to retain the prior plain-text formatting.

**Comment by jungshadow** [comment]
@cjerdonek I'm still feeling pretty good about nixing HTML. Let's keep going down that road :)

**Comment by cjerdonek** [comment]
Fine with me!

**Comment by jdmgoogle** [comment]
I love coming to work in the morning and finding a lengthy discussion thread that agrees with my thinking on an issue. :)

**Comment by pstenbjorn** [comment]
Looks like so far we have a consensus.

**Comment by jdmgoogle** [comment]
This issue appears to be decided: no HTML.
