### ISSUE TITLE
Document ContactInformation

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#175]
Finish documenting `ContactInformation`. I marked this also as a question, but it's more of a statement about `identifier`:

```xml
<xs:complexType name="ContactInformation">
  ...
  <xs:attribute name="identifier" type="xs:string" use="required" />
</xs:complexType>
```

Reading back through #144, I think we may have put the cart before the horse. I'd prefer @nomadaisy and/or @pkoms weigh in on this convention, since they're in charge of "CSV-ing" the spec. If they think this idea works the best for them...great and I'll shut up :) /cc @MariaDemocracyWorks

**Comment by pkoms** [comment]
We do need CSV support for ContactInformation. The XML description is fine. I think our process suggests I should close this and open a separate issue for CSV support for ContactInformation, but @jungshadow, can you confirm before I do?

**Comment by jungshadow** [comment]
@pkoms As soon as #176 is merged, this issue will auto-close. If you want to start a discussion about how to deal with ContactInformation, et al in CSVs, we should add a milestone w/deadline for the CSV format and start assigning issues to it. Cool?
