### ISSUE TITLE
Keep sample feed synced with spec

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#179]
This is an issue that should be kept open until 5.0 is officially released. It is here to remind us to keep the sample feed synced with the spec itself. Any PRs which fix the sample feed from earlier breakages should reference this issue.

**Comment by jdmgoogle** [comment]
Items that need to be added to the sample feed:

1. Ballot measure contests;
2. Retention election (Utah 2014 sample data);
3. Judicial elections (compare/contrast LA elections with item (2));
4. Internationalized text;
5. Early voting sites;
6. Combination early voting site/election-day voting site;
7. Drop boxes;
8. Mail-only precincts;
9. A `LatLng` in a  `PollingLocation`.

**Comment by jungshadow** [comment]
@jdmgoogle Hope you don't mind that I changed your numbered list into a todo list. Just thought it might be easier to tick off the things when they were finished :)

**Comment by jdmgoogle** [comment]
Moving this to "5.0 Documentation" since it has to do with the sample feed. The only item left is for me to examine how LA's judicial elections may be different than retention elections.

**Comment by jdmgoogle** [comment]
Barring any last-minute changes because of #268 (which is highly unlikely) this will get closed out soon.
