### ISSUE TITLE
Should candidates have a status?

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#18]
One of the ideas I've been toying with for a while is having a status identifier for candidate elements. We receive data late because states would like to wait until the candidate have been certified, but I feel we're missing a teachable moment about the time when a candidate files to when they're certified to be on the ballot. This may also help in situations where the candidate is on the ballot but has withdrawn from the race. Possible values could be:

* Filed
* Certified
* Challenged
* Withdrawn

I'm not sure all of these would be easy to get from the current systems and I would definitely welcome additional thoughts about this change.

**Comment by jktomer** [comment]
I don't really see states being willing to supply ballot data for not-yet-certified candidates even if we allow them a way to specify it, but we'd certainly be happy to consume such data were it available.

**Comment by cjerdonek** [comment]
In San Francisco at least, there is also a status of "Qualified Write-In."  These are candidates whose names do not appear on the ballot, but whose votes will be tabulated if they are marked in the write-in space.  Because the names of these candidates do not appear on the ballot (and because I believe the names must be spelled correctly), each polling place is required to display a sheet listing the names of the qualified write-ins.

I'm not sure off-hand what level this is for (municipal, state, federal, etc).

**Comment by MariaDemocracyWorks** [comment]
I think this is interesting, but like Jared mentioned, I'm not sure how many of the EMS systems you could pull these labels from. We generally don't get data before the candidates are certified, though if we were able to display this data, maybe that would change.

**Comment by cjerdonek** [comment]
The City and County of San Francisco uses DFM's EIMS for its EMS (which is one of the major EMS's in the country), and I'm pretty sure it's set up to store information about the various filing stages that a candidate is in (e.g. dates certain paper forms were submitted, etc).  I could find out for sure if people are interested.

As evidence, here is an HTML table on the Department's web site with the dates that various local candidates filed their "Declaration of Intent": http://www.sfgov2.org/index.aspx?page=4701

**Comment by jungshadow** [comment]
@MariaDemocracyWorks We don't receive candidates because they aren't finalized, but, if we had a mechanism to track and display candidate status, we may be able to convince folks to release the data earlier. I'm sure it would still take some convincing, but, we don't have the fields, we definitely can't.

@cjerdonek Thanks for the info and for looking into it.

We're going to try and fit the 1622.2 ballot models into VIP, so the structure of every thing may change soon.

**Comment by pstenbjorn** [comment]
@jungshadow maintaining candidate status would assume multiple iterations of candidate data loading.  I am for it in general and agree with you that some of this will be addressed as we look toward 1622.2 interoperability.

**Comment by pkoms** [comment]
I like the idea of getting statuses, but it seems likely to open us up to alarm from state partners and campaigns when we get 2-3 days out of date, which is more likely to happen the more granular our statuses are. It's a downstream issue, but I think could potentially be a major one.

**Comment by jungshadow** [comment]
@pkoms This should only be included in states where the update process is constant. There's a huge amount of reward that I personally believe outweighs the risk, but it's the project's responsibility to ensure it's correctly handled. I think we can put protections in place if the data becomes stale (e.g. strip candidate data from a given feed or similar). Additionally, we could reduce the number of statuses, if that would make things more simple.

**Comment by jdmgoogle** [comment]
Given that the 1622.2 ballot info has both pre-election and post-election status information, can we consider this closed?

**Comment by jdmgoogle** [comment]
Since there haven't been any comments on this (and we're porting over 1622.2 elements) I'm marking this closed. Although feel free to re-open if you feel this need further discussion.
