### ISSUE TITLE
CSV Support for ContactInformation

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#185]
Now that ContactInformation has been made free-floating, it needs its own flat file and set of linking flat files.

I believe the complete list is: 
ContactInformation
Source_ContactInformation
ElectionAdministration_ContactInformation
VoterService_ContactInformation
Office_ContactInformation

**Comment by jktomer** [comment]
Can the contact info be inlined in the CSVs? That seems more useful, from a CSV creator's perspective.

If there can be more than one ContactInformation per CSV record _in practice_ -- regardless of what's technically allowed in the XML spec -- then this wouldn't work. But my instinct is that for the CSV format you'd want as few files as practical.

I don't actually ever deal with the CSVs, though, so feel free to tell me I'm wrong :)

**Comment by afsmythe** [comment]
The `contact_information` [csv documentation](https://vip-specification.readthedocs.io/en/latest/built_rst/csv/elements/election_administration.html#contact-information) should be updated to more clearly document how the `contact_information.parent_id` is used to resolve the issue here.

**Comment by afsmythe** [comment]
This is resolved by PR https://github.com/votinginfoproject/vip-specification/pull/363
