### ISSUE TITLE
Element odd_even_both should be required and documented implementation should recommend discarding segment if invalid/missing

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#19]
Currently, the `odd_even_both` element on `street_segment` is optional and the implementation states:

> If the odd_even_both field is not present or invalid, the implementation is required default to odd.

In future versions of the spec, the element should be required and, to mitigate any issues on the back end, ignore the entire street segment if missing or invalid.

**Comment by jungshadow** [comment]
@nomadaisy Flagging this conversation for you, since you're working on the docs.

**Comment by jdmgoogle** [comment]
This now seems to be required, per the vip5 branch spec. Where do we stand on the documentation?

**Comment by jungshadow** [comment]
@nomadaisy I'll let you close if the docs are up-to-date on this.
