### ISSUE TITLE
Import VIP 3.0 CSV Specification To Use As Baseline CSV Specification

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#190]

**Comment by jungshadow** [comment]
Thinking aloud, are you sure you want to start with the 3.0 CSVs? I'm wondering if it's easier to start fresh, considering the number of changes.

**Comment by pkoms** [comment]
I can see it either way. Paging @nomadaisy: which do you prefer?

**Comment by nomadaisy** [comment]
We might as well start fresh, which should be about the same amount of work.

**Comment by pkoms** [comment]
Closing.
