### ISSUE TITLE
Document HoursOpen

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#197]
Document and provide examples for the `HoursOpen` element.

**Comment by jungshadow** [comment]
@jdmgoogle Whoops...I'd started filling this out, when I noticed that you'd assigned yourself. How far did you get?

**Comment by jdmgoogle** [comment]
See PR #205. :)

**Comment by jungshadow** [comment]
Just saw that. Should have checked the assignees before starting on it. _Mea culpa_.

**Comment by jdmgoogle** [comment]
No worries. Sorry I wasn't more explicit about claiming this. I'm now working on #202.

**Comment by jungshadow** [comment]
Nope...still my bad. Should have checked. We have these systems so you don't have to be ridiculously explicit :)

**Comment by jdmgoogle** [comment]
Closed by #205.
