### ISSUE TITLE
Misstatement on referendum ballot response items in spec

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#20]
http://votinginfoproject.github.io/vip-specification/#referendumitems :+1: 
"If no ballot_response_id field is invalid, the implementation is required to ignore the referendum element containing it."

Should maybe be: "If no ballot_response_id field is present or the field is invalid, the implementation is required to ignore the referendum element containing it."

**Comment by jungshadow** [comment]
@nomadaisy Is this fixed and ok to close?

**Comment by nomadaisy** [comment]
Fixed and closed
