### ISSUE TITLE
Document PartyContest and PartySelection elements

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#202]
Document the `PartyContest` and `PartySelection` elements.

I'm putting both of these in one item since they're just extensions of `ContestBase` and `BallotSelectionBase`, respectively, with no additional modifications.

**Comment by pstenbjorn** [comment]
@jdmgoogle in going through my example today it seems that the element `PartyId` is missing from `PartyContest` unless I am missing something.

**Comment by jdmgoogle** [comment]
Closed by #206.
