### ISSUE TITLE
Add a Name element to Election

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#219]
Late addition to the spec, but one of the things we continue to run into is what a particular election is called. All the ancillary information in `Election` is important, but doesn't communicate a user-friendly name for the upcoming event. My thoughts:

* It should be Optional for now, but move to **Required** after we upgrade folks from 3.0 to 5.0;
* The type should be `InternationalizedText`;

The wrinkle is that we roll lots of elections into a single feed, so, for lower-level elections in states that don't consolidate, the name of the election may be hard to figure out or obnoxiously long if the result is a concatenation of all the events.

I'd like to be able to shoehorn this thing in before we push this out the door. Thoughts?

**Comment by pstenbjorn** [comment]
Yes!  I agree this is needed and can explore uses of the data element in future discussions.

**Comment by jungshadow** [comment]
Cool. I don't mind taking this on, but I'll wait for @jdmgoogle to weigh in on this (**NB:** not omitting anyone else who'd like to weigh in).

Here's what I'm thinking:

```xml
<xs:element name="Election" minOccurs="1" maxOccurs="1">
  <xs:complexType>
    <xs:all>
      ...
      <xs:element name="IsStatewide" type="xs:boolean" minOccurs="0" />
      <xs:element name="Name" type="InternationalizedText" minOccurs="0" />
      ...
    </xs:all>
    <xs:attribute name="id" type="xs:ID" use="required" />
  </xs:complexType>
</xs:element>
```

**Comment by jdmgoogle** [comment]
Sounds good to me.

**Comment by jungshadow** [comment]
[Excellent](http://bukk.it/ehhhhhhksellent.gif). I'll make a pull request that updates both the spec and the docs.

**Comment by jungshadow** [comment]
Make that: "the spec, the docs, and the sample feed."
