### ISSUE TITLE
Better handling of apartments / multi-home lots

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#22]
VIP needs to handle apartments / multi-home lots better. My recommendation:

Instead of start_ and end_apartment_number, street segments should have only a single value, apartment_number. Each residence in a multi-residence lot could then be represented as its own address point.

**Comment by jungshadow** [comment]
@pkoms Thoughts on whether this should be `street_segment.apartment_number` or `street_segment.unit_number` to make it more generic (NB: I'm not sure if "unit" is the appropriate term if it carries other legal definitions, but it seems generic to me). We're looking into other addressing standards, but I didn't want to dismiss this idea, either, especially if the standards still need to account for this case.

**Comment by pkoms** [comment]
```street_segment.unit_number``` is probably better. Good catch.

**Comment by jungshadow** [comment]
Explicitly dding @jdmgoogle and @pstenbjorn to this conversation given our discussion on addressing standards.

**Comment by jktomer** [comment]
Some large buildings (and this is only likely to be relevant for fairly large buildings, I think) will have a *lot* of unit numbers, leading to significant street segment inflation in the case of building-dividing precinct boundaries.

I'm not necessarily opposed to this, but it's worth pointing out.

Also, note that our service is pretty poorly suited to dealing with unit numbers at all right now, and any building that ends up being split in such a way will likely get dropped from Google Civic Information API coverage entirely for at least the near future. That doesn't mean the spec shouldn't be made to support it properly though!

**Comment by pkoms** [comment]
I know it'll drive street segment inflation, but that seems like a fair price to pay to support these voters.

Good point that this won't immediately fix the problem. As it is, though, these buildings are getting dropped for being duplicate street segments. Being unable to support unit numbers won't make our situation any worse than the present.

**Comment by pstenbjorn** [comment]
This will be committed 

    <xs:element name="street_segment">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="start_house_number" type="xs:integer" />
              <xs:element name="end_house_number" type="xs:integer" />
              <xs:element name="odd_even_both" type="oebEnum" />
              <xs:element name="non_house_address" type="detailAddressType" />
              <xs:element name="unit_number" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
              <xs:element name="precinct_id" type="xs:string" />
              <xs:element minOccurs="0" name="precinct_split_id" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>

**Comment by jungshadow** [comment]
Looks good to me. @pkoms?

**Comment by pkoms** [comment]
Looks good to me too.

**Comment by pstenbjorn** [comment]
Great.  Look for a pull request that will close this issue..

**Comment by pkoms** [comment]
Can we hold on closing the issue until we have an analogous CSV proposal? I should have it in by EoW.

**Comment by pstenbjorn** [comment]
@pkoms works for me.

**Comment by jungshadow** [comment]
@pkoms are you sure you want to start the CSV proposals, now? While street_segment should be one of the few stable elements, it may be wise to wait until we have a solid XML prototype.

**Comment by pkoms** [comment]
It's one of my open to-dos from the VIP Issues Agenda, but I can defer.

**Comment by jungshadow** [comment]
@pkoms I might advise it. We're moving pretty quickly and there are some large-scale changes on the horizon. Although, to play my own devil's advocate, it may be worthwhile to start the process to see if anything sets off an alarm for being too cumbersome/difficult for data collection.

**Comment by pkoms** [comment]
Right -- I expect that this won't get too cumbersome, so I'm okay deferring it. I'd like to keep Noma's review of CSV implementations of multiple languages open, because I'm afraid that one could get out of hand.

**Comment by jungshadow** [comment]
@pkoms That's fine, but you or @nomadaisy should make that comment in the correct issue (i.e. #39) otherwise it'll get lost.

**Comment by cjerdonek** [comment]
@pkoms @jungshadow Could one of you briefly describe what needs to be worked out for a CSV implementation (if it's possible to say so briefly)?  I just wanted to understand for the purposes of helping with #39.  Thanks a lot.

**Comment by pkoms** [comment]
@cjerdonek I'm going to follow up in #39.

**Comment by jdmgoogle** [comment]
This appears to be fixed in the vip5 branch. Do we have a final resolution about how to handle this in the CSV? The issue to which @pkoms linked has been marked as closed but I didn't see anything in there (in my quick-ish skim) about apartments in CSV format.

**Comment by pkoms** [comment]
CSV changes will be addressed later. Closing.
