### ISSUE TITLE
Alphabetize elements inside the root VipObject

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#237]
I noticed that the elements inside the root VipObject still need to be alphabetized per [this section](https://github.com/votinginfoproject/vip-specification/blob/vip5/STYLEGUIDE.md#elementattribute-ordering) of the style guide.  The fact that they weren't made it a bit harder to work on issue #192.

**Comment by jdmgoogle** [comment]
SGTM (per my LGTM in #237).

**Comment by cjerdonek** [comment]
Addressed by PR #239.
