### ISSUE TITLE
Small changes to documentation

### ISSUE THREAD

**Issue by nomadaisy** [votinginfoproject/vip-specification#238]
I found the following small documentation issues to fix, most of which are consistency issues:

- [x] BallotMeasureContest text description, "Extends extends ContestBase" should delete the second "extends"
- [x] Inconsistent handling of URI (uri) vs. URL (url). Examples of elements with old descriptions using URL: Election, ElectionAdministration, Source
- [x] Inconsistent listing of "element" vs. "field" in Error Handling columns. Examples of elements with this issue: BallotMeasureContest, ContestBase, Election
- [x] Inconsistent casing of element name in Error Handling column in Locality.
- [x] Inconsistent formatting of element names in text description and tables. Examples of elements with this issue: ElectoralDistrict has the element formatted as `ElectoralDistrict`, whereas elements like Candidate do not have their names formatted.
- [x] Inconsistent message for Error Handling column in Election element for the two required fields: Date and StateID
- [x] State element description for PollingLocationID should change from "...they can be specified here, but are encouraged to only..." to "they can be specified here, but you are encouraged to only..."
- [x] Name field in State element is listed as Optional, but the Error Handling column message reads as if it is Required.
- [x] StreetSegment text description should change from "...of only one address in which case..." to "...of only one address, in which case..."
- [x] Inconsistent listing of element name in StreetSegment Error Handling column. Examples of two different styles: StreetSegment vs. street segment
- [x] Is it possible to specify that we want the VipId column of Source to be the FIPS code? Can we link to the list of FIPS codes?
- [x] The Description field of the table for Source describes the DateTime as, "This datetime is required to match the datetime specified in the feed’s filename.", which does not match the documentation on what the filename should be. For example, the sample feed name instructions: https://github.com/votinginfoproject/vip-specification/blob/vip5/sample_feed.xml

**Comment by jungshadow** [comment]
> Inconsistent listing of "element" vs. "field" in Error Handling columns. Examples of elements with this issue: BallotMeasureContest, ContestBase, Election

@nomadaisy Thanks for being thorough with the doc issues. Hard to address all of this here, but I did want to make one note on the quoted section above. I aimed to be intentional with how I talked about "fields" vs "elements" (_**NB:** I'm a bit behind on updating the styleguide_). I used "field" when talking about an element that takes a single value (e.g. `State.Name`) and "element" when talking about a complex structure (e.g. `Election.Name`). Hope that makes sense.

**Comment by cjerdonek** [comment]
I just want to say that PR #255 addresses a number of the items in this checklist (and in a DRY and automated way), especially around the error-handling column.  For example, it automatically chooses correctly between "field" and "element" (item 3).  It automatically uses the correct casing of the element name (item 4 re: Locality and item 10 re: StreetSegment).  And it correctly chooses the language based on whether the tag is optional or required (item 8).

Also, all of these things can easily be tweaked globally in one place if you ever want to modify the standard phrasing or formatting, etc.

**Comment by jdmgoogle** [comment]
@cjerdonek For the moment I'm going to assign this to you since it sounds like several of these items will get fixed once we roll in #255. After you submit #255 (or its next iteration) please check off the items which were resolved by that PR and then assign this issue to either @jungshadow or myself, please.

**Comment by jdmgoogle** [comment]
Closed by #274.
