### ISSUE TITLE
Confusing error message following xmllint instructions

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#240]
The CONTRIBUTING docs say to run:

    $ xmllint --postvalid --nonet --xinclude --noout --schema vip_spec.xsd sample_feed.xml

However, when I run this I get the following unhelpful, self-contradictory message:

    validity error : no DTD found!
    Document sample_feed.xml does not validate
    sample_feed.xml validates

(Following the online validation instructions, I got no errors.)

**Comment by jdmgoogle** [comment]
The last line is the one that matters. It can't find a DTD (which is fine, since we're using an XSD instead of a DTD), and originally fails to validate because of that. Then it realizes everything's okay because it has a schema.

I tend to use [jing](http://www.thaiopensource.com/relaxng/jing.html) in addition to `xmllint` since that actually checks the ID/IDREF values.

Should we update the documentation to show that this confusing message actually means "success"?

**Comment by cjerdonek** [comment]
Yeah, I think including a sample of the expected output and adding a note to ignore the first two lines would be a fine way to go:

    validity error : no DTD found!
    Document sample_feed.xml does not validate
    sample_feed.xml validates

Regarding the ID/IDREF values, I was finding that xmllint was also noticing bad values, though it doesn't seem to notice _all_ bad values, which was strange.  I'm not sure I know the pattern of which errors it was able to find and which it wasn't.

**Comment by cjerdonek** [comment]
Oh, and better yet would be if xmllint has a flag to make the spurious error go away.  I didn't find one on a quick scan of the help though.

**Comment by cjerdonek** [comment]
FYI, if I remove `--postvalid` and just run--

    $ xmllint --nonet --xinclude --schema vip_spec.xsd --noout sample_feed.xml

It works without the spurious message and seems to catch errors okay.  Is there a case where `--postvalid` is necessary to catch something?  ([Here](http://fahdshariff.blogspot.com/2011/10/validating-xml-with-xmllint.html) is where I saw an example of checking against an XSD rather than a DTD.)

**Comment by jdmgoogle** [comment]
I *thought* that `--postvalid` was necessary to get it to cross-check the `xs:ID` and `xs:IDREF` values, but ... perhaps not? I've been using jing to do that:

http://www.thaiopensource.com/relaxng/jing.html

There are packages (at least) for Debian/Ubuntu and Fedora, and probably others. Let me know if it's (a) available, and (b) works for you on whichever distro you're using.

**Comment by cjerdonek** [comment]
No, `--postvalid` doesn't seem to check ID and IDREF references (I just tried it).  The only ID / IDREF errors I've ever gotten are like the following:

    Element 'LocalityId': '1' is not a valid value of the atomic type 'xs:IDREF'.

But that error occurs with or without `--postvalid`.  So I don't know of any additional checks that occur with `--postvalid`.

**Comment by jdmgoogle** [comment]
Removing `--postvalid` appears to have cleared it up. I also added a comment about and link to `jing` in case people would like to run that, too.
