### ISSUE TITLE
FileDate should be xs:date not xs:dateTime?

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#241]
See title.  The sample feed doesn't have an example.  But it requires HH:MM:SS to validate.

**Comment by cjerdonek** [comment]
If the element should be xs:dateTime, then it would be much better and less confusing if it were called something that "FileDateTime" or "FilingTime".

**Comment by jdmgoogle** [comment]
Correct, `FileDate` should be `xs:date` instead of `xs:dateTime`.

**Comment by cjerdonek** [comment]
I created PR #244 for this.

**Comment by cjerdonek** [comment]
Closed by PR #244.
