### ISSUE TITLE
Document whether AddressLines should include the name

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#243]
I think the documentation for ContactInformation.AddressLine should say whether the address lines should include the "name," which also appears as ContactInformation.Name.  For example, here is the address for the SF Department of Elections:

> Department of Elections 
1 Dr. Carlton B. Goodlett Place, Room 48 
San Francisco, CA 94102

Since "Department of Elections" is already appearing as the ContactInformation "Name," does this mean that the name should be excluded from the address lines, or should the name still be the first AddressLine?

**Comment by cjerdonek** [comment]
My instinct is that the AddressLines should be self-contained and include the name, e.g. since the "name" might not always be the first address line.

**Comment by jdmgoogle** [comment]
I disagree. Most elements with a `ContactInformation` field also have a `Name` element.

**Comment by cjerdonek** [comment]
> Most elements with a ContactInformation field also have a Name element.

Yes, I know that (and said that in my OP).  My question is about programmatically creating an address label from the information in ContactInformation.  The two options I described are--

1. Concatenate "Name" and "AddressLines", or
2. Only use "AddressLines" (i.e. the AddressLines should make up a stand-alone address label).

I think (2) is better because it is simpler and more flexible, letting one specify exactly how things should be addressed.  For example, on the [California Secretary of State's Office](http://www.sos.ca.gov/administration/contact-information#elections), their complete mailing address is listed as--

    Elections Division
    1500 11th Street, 5th Floor
    Sacramento, CA 95814

However, we probably wouldn't want to list "Elections Division" as the "ContactInformation.Name" for the California Secretary of State's Office.

**Comment by jdmgoogle** [comment]
> My question is about programmatically creating an address label from the information in ContactInformation. 

How often are users trying to create an address label? This isn't a flippant question, I'm actually curious as to whether or not this is a common use case.

> However, we probably wouldn't want to list "Elections Division" as the "ContactInformation.Name" for the California Secretary of State's Office.

The link you provided says that the SoS's office actually has multiple divisions, in which case it makes sense for the name to be "Elections Division" or "Secretary of State, Elections Division".

**Comment by jdmgoogle** [comment]
I'm moving this discussion to the "5.0 Documentation" milestone, since this is how we *use* the feed, not necessarily the spec itself.

**Comment by jdmgoogle** [comment]
Ping @cjerdonek. Do you have any insight or feedback on the questions I posted?

**Comment by jdmgoogle** [comment]
Assigning this to @pstenbjorn so he can include it in #45, the "best practices" guide.

**Comment by cjerdonek** [comment]
> How often are users trying to create an address label?

@jdmgoogle One use case I had in mind was if someone wanted to mail something to each election official providing VIP data.  They would need to know how to programmatically construct the labels from the feed data.

Similarly, if someone wanted simply to _display_ the address on a web site (as opposed to actually mailing something), there is a similar ambiguity.  If the feeds are inconsistent in how they provide AddressLines, it could result in addresses like the following (with a duplicated name portion):

    Secretary of State
    Secretary of State
    1500 11th Street, 5th Floor
    Sacramento, CA 95814
    
Or else the following (with no identifying name portion):

    1500 11th Street, 5th Floor
    Sacramento, CA 95814

> The link you provided says that the SoS's office actually has multiple divisions...

I was wrong in what I said about the SoS page.  The web site says this at the top:

    California Secretary of State
    [Include division or program name]
    1500 11th Street
    Sacramento, CA 95814

So in the case of the Elections Division, the full address (with name) would be the following:

    California Secretary of State
    Elections Division
    1500 11th Street, 5th Floor
    Sacramento, CA 95814

**Comment by jdmgoogle** [comment]
Hrm. Personally I'm of the opinion that the `AddressLine` values should contain the parts of the street address as opposed to the name of the place, since that's what the `Name` field is for. Perhaps the `Name` field should be repeated to allow for multi-line names (such as your second example). I'm open to feedback from @jungshadow @jen-tolentino @pstenbjorn @jktomer (the latter of which is OOO for a while, but still) etc etc.

**Comment by cjerdonek** [comment]
Another option would be to add a "NameAddressLines" tag which would let one separate the "street" portion from the name portion.

**Comment by jdmgoogle** [comment]
Paging @jungshadow @pstenbjorn @jen-tolentino to get more voices.

**Comment by pstenbjorn** [comment]
@jdmgoogle a potential solution would be to change `Name` to unbounded and treat it like address.  In most instances though, the current structure of a name field followed by n-number of `AddressLine` elements.  However there are addresses where the name of a building is part of the address required for delivery or specificity in that case it should be an address line.

In short, IMO, the standard as currently designed should handle the majority of addresses and if we choose in future releases to include multiple `ContactInformation` `Name` elements it should handle the boundary use cases.

**Comment by cjerdonek** [comment]
Note that there are at least two use cases that need to be satisfied: (1) including the "name" in text like in a sentence, and (2) showing an address with the name portion in the first lines and the street address portion in subsequent lines.  If "name" is made a multi-line element, then it wouldn't be clear how to use that information in the first use case (1).  For example, would the instructions be to join all the lines together with a comma in between, or use some other approach?  To be on the safe side, it seems like those two use cases should be served by separate elements.

**Comment by jdmgoogle** [comment]
Paging @jungshadow and @jen-tolentino for their opinions.

**Comment by jungshadow** [comment]
With a combination of a minimal approach and the best practices document, I think we can use @pstenbjorn's suggestion to make `Name` unbounded. I understand your concerns, @cjerdonek, but I'd rather not get caught up too much on this considering that address standards are barely standards and we probably won't capture all of the edge and use cases until this is operating in the wild and vetted by many more people.

**Comment by jdmgoogle** [comment]
Here's my proposal:

1. For version 5.0 leave the elements as they are, and update the best practices to provide some guidance as to what should go in `Name` versus what goes in `AddressLine`.
2. File a bug against version 5.1 to reevaluate whether this is working.
3. Go through the 2015 cycle and see how the incoming data looks.
4. After the 2015 cycle, discuss on the bug from step 2 if there are issues with data quality, and whether they need to be addressed with changes to the best practices document, the standard itself, or both.

How does this sound?

**Comment by jungshadow** [comment]
![Image of an owl with the word SUPERB](http://bukk.it/superb.jpg)

**Comment by cjerdonek** [comment]
Okay, for (1), I think an important thing to do in the best practices guide and/or the element documentation itself would be to say what `Name` and `AddressLine` should look like for a real-world example like the following:

    California Secretary of State
    Elections Division
    1500 11th Street, 5th Floor
    Sacramento, CA 95814

**Comment by jdmgoogle** [comment]
> Okay, for (1), I think an important thing to do in the best practices guide and/or the element documentation itself would be to say what Name and AddressLine should look like for a real-world example like the following:

I agree.

**Comment by jdmgoogle** [comment]
I filed #267 to meet step (2) of the plan.

@cjerdonek Could you take a stab at describing the Name/AddressLine best practices? It doesn't have to be perfect, but just put a stake in the ground.

I know this isn't your preferred solution, but rather than have me come up with something that doesn't quite align with your feelings about what goes where, could you give it a shot and we'll go from there?

**Comment by jdmgoogle** [comment]
Also, @jungshadow, I just noticed that that's the Superb Owl.

![image](https://cloud.githubusercontent.com/assets/10949127/9382756/814fe8a2-4711-11e5-99ba-3668b47b6364.png)

**Comment by jungshadow** [comment]
Oh it's on now, @jdmgoogle!
![gif of a kangaroo dropping a ball](http://bukk.it/gotime.gif)

**Comment by jdmgoogle** [comment]
@cjerdonek Just a quick ping to see if you can take a stab at updating the "best practices" doc to provide guidance, per [the earlier comment.](https://github.com/votinginfoproject/vip-specification/issues/243#issuecomment-132985839)

**Comment by cjerdonek** [comment]
Sure (and sorry for the delay), I'll try to rough something out by tomorrow.

PS - I would never be able to compete with you guys on GIFs!

**Comment by jungshadow** [comment]
@cjerdonek It's actually a second language for us, so no worries ;)

**Comment by cjerdonek** [comment]
I created PR #271 for this.

**Comment by cjerdonek** [comment]
Closed by PR #271.
