### ISSUE TITLE
ElectionAdministration.Department error handling

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#245]
Currently, the presence of one bad Department in an ElectionAdministration breaks the entire object. I understand wanting at least one functional Department in the ElectionAdministration, but might it make more sense to require only one valid Department, and have only the relevant Department break if a subsequent one is invalid?

**Comment by cjerdonek** [comment]
Is this even possible -- i.e. to indicate in an XSD that some element doesn't need to "validate"?

**Comment by pstenbjorn** [comment]
@pkoms if I understand your suggestion, this would require the creation of another element in the schema (for the primary `Department` that would require all valid elements) and then another element where fields were optional.  What are the elements that are causing the the invalid `Departments`?

**Comment by cjerdonek** [comment]
> and then another element where fields were optional.

FYI, from what I can tell, everything is already optional.

**Comment by pkoms** [comment]
Chris, you're right that all fields are optional. Given how much of a pain it would be to fix, can we at least change the error handling language to make sense given the 1+ nature of Departments?

**Comment by cjerdonek** [comment]
@pkoms I think what @pstenbjorn is asking is what types of errors are you getting in the subsequent Departments.  Are there many types of errors or just a couple?  And in either case, what are some of them?

**Comment by pkoms** [comment]
Ah, I see what wasn't clear. My first sentence should have had an "According to the documentation..." Let me restate.

Currently, the documentation suggests that one bad Department in an ElectionAdministration should break the entire object. I understand wanting at least one functional Department in the ElectionAdministration, but I thought it might make more sense to require only one valid Department, and have only the relevant Department break if a subsequent one is invalid. Since that seems strenuous, I'm recommending only that the language describing Department error handling in ElectionAdministrations* should be revised to make more sense in the context of Departments being 1+, instead of 0-1. Does that make more sense?

*"If the element is invalid or not present, the implementation is required to ignore the ElectionAdministration object that contains it."

**Comment by cjerdonek** [comment]
Oh, okay, thanks.  That seems more like a processing issue rather than an issue with the XSD.  So you want to say something like the following?

> If the element is not present or the first one is invalid, then the implementation is required to ignore the ElectionAdministration object that contains it.  The implementation is required to ignore any invalid elements after the first.

If this is the case, then implicitly the first department must be the _primary_ one.  I would also add that fact in the "Description" column.

**Comment by pkoms** [comment]
I think my ideal is:

>If an ElectionAdministration object contains no valid Department elements, then the implementation is required to ignore it. If an ElectionAdministration object contains at least one valid Department element, then the implementation is required to ignore all other, invalid Departments.

But I don't know if that's infeasible from a processing perspective. @jdmgoogle thoughts?

**Comment by jdmgoogle** [comment]
Paging @jktomer to discuss the processing side of things.

**Comment by jdmgoogle** [comment]
Ping @jktomer.

**Comment by jktomer** [comment]
TBH I don't like leniency in specs. It encourages people to leave things broken.

But I'm fine, I suppose, with the documentation stating that broken-but-XML-clean Departments will be ignored, and ElectionAdministrations with at least one non-broken Department will be accepted (and our pipeline actually behaving that way).

**Comment by jdmgoogle** [comment]
Assigning this to @cjerdonek to see if this gets fixed in #255. If not, reassign back to @jungshadow or myself.

**Comment by jdmgoogle** [comment]
Closed by #274.
