### ISSUE TITLE
ElectionAdministration.Department.ElectionOfficialPersonId single vs. multiple

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#246]
From having spent too much time on state election official lists, I know that the lists sometimes find it  important to list not only the head person, but also deputies, co-heads, associate vice-deputies, etc. Is there any reason not to make ElectionAdministration.Department.ElectionOfficialPersonId capable of repeating?

**Comment by cjerdonek** [comment]
Seems reasonable to me.

**Comment by jdmgoogle** [comment]
@pkoms Can you provide an example of a situation where we would not want to list separate `Department` objects but have multiple people within that `Department`? My understanding behind the purpose of breaking things into different Departments was to support this type of granularity.

**Comment by jdmgoogle** [comment]
Ping @pkoms.

**Comment by jdmgoogle** [comment]
Closing this one out. Someone can re-open if we feel it's necessary, but I'd like to get this out the door ASAP.
