### ISSUE TITLE
Support for per-precinct EV sites

### ISSUE THREAD

**Issue by pkoms** [votinginfoproject/vip-specification#247]
I'm sorry I didn't catch this sooner, but on the Precinct documentation, we specify "Multiple **PollingLocationId** tags may be specified, but this use should be reserved for when multiple Election-Day-only vote locations serve specific precincts."

There is such a thing as a per-precinct early vote site. For example, in Coconino County, AZ, in November 2014, aside from the county-wide EV site, individual precincts had 0, 1, or 2 early vote sites. The precincts with two sites, at least, would violate the documentation. There's at least one other state that had some per-precinct EV sites, but I can't recall which off the top of my head.

In light of this, can we either remove or soften that language?

(To see a full list of the EV sites in Arizona in 2014, you can go here: https://data.votinginfoproject.org/hand-collected/vipEV-04-2014-11-04.zip )

**Comment by jktomer** [comment]
That just seems like a documentation bug; there's no reason as far as I can tell not to have multiple early voting sites attached to a precinct, and we plan to support this.

**Comment by jdmgoogle** [comment]
I second @jktomer's comment. We support per-precinct early voting sites. The documentation simply needs to be updated.

Handing it off to @jungshadow to fix or delegate as necessary.

**Comment by jdmgoogle** [comment]
Handing this off to @cjerdonek so he can say if this gets fixed with #255 or not. If it doesn't, then reassign to either @jungshadow or myself.

**Comment by jdmgoogle** [comment]
Closed by #274
