### ISSUE TITLE
Provide documentation as a single page

### ISSUE THREAD

**Issue by JohnArntz** [votinginfoproject/vip-specification#248]
Hello.  As an elections official it would be most helpful to  be able to view the list of objects and fields on one screen or page without having to click through many pages and also read code (XML).  If I were to have a list of objects and fields that I can easily reference without having to know how to read code (human readable, in other words), it would better facilitate my providing pertinent information in open data formats.  Then, those who do code using this information would have more content to develop.

**Comment by jdmgoogle** [comment]
@JohnArntz Hi, welcome to the VIP GitHub!

That definitely seems like a good request. @cjerdonek or @jungshadow, would we be able to script something like this?

**Comment by cjerdonek** [comment]
@jdmgoogle Yeah, my sense is that this should be pretty doable.  After poking around, it might not even require any scripting (e.g. perhaps using multiple "include" directives in an `xml/single_page.rst`).  I should be able to help with this and will have more time to start taking a look next week or so.

**Comment by jdmgoogle** [comment]
@cjerdonek Thanks. Assigning this one to you for now.

**Comment by jdmgoogle** [comment]
Ping @cjerdonek: have you had a chance to look into this?

**Comment by cjerdonek** [comment]
> Ping @cjerdonek: have you had a chance to look into this?

@jdmgoogle Just catching up on these pings.

My plan for this was to wait until PR #256 was resolved before digging in -- in case the changes involved would be conflicting.  There is a chance that this issue will require some restructuring / moving things around in some form, so I didn't want to have two such PR's in play at once.

**Comment by jdmgoogle** [comment]
@cjerdonek Just looping you back in to get a sense of your current workload and availability for 5.1 stuff.

**Comment by cjerdonek** [comment]
I'll have some time.  It's on my todo list in particular to work on this issue, as well as a couple of the other "build" related issues.  I expect to start working on those within the next couple weeks or so.

**Comment by cjerdonek** [comment]
I didn't see an issue for it (the discussion might only have been by e-mail), but the first thing I was going to do is move the header / footer / etc stuff to the YAML like you had suggested, @jdmgoogle.

**Comment by jdmgoogle** [comment]
@cjerdonek Okay, good to know. We should probably have a meeting this week just to scope out VIP 5.1 in general. If it's not this week, next week likely won't work (pre-Thanksgiving vacation), and then it's December.

**Comment by cjerdonek** [comment]
FYI, I started work on this [here](https://github.com/cjerdonek/vip-specification/tree/feature/single-page) in a local branch.  It is more or less working right now, except I need to do a little more work on the labels / cross-references so that they will work with more than one "version" of the docs.  Basically, the ref names need to be disambiguated with a prefix.  I have a way to do this in mind, I just need to finish implementing it.

**Comment by cjerdonek** [comment]
Okay, this was completed by PR #302.  The single-page version can be seen on GitHub [here](https://github.com/votinginfoproject/vip-specification/blob/vip51/docs/built_rst/xml/single_page.rst) (though that is just the "raw" version -- it isn't yet live on the public documentation page [here](http://vip-specification.readthedocs.org/en/vip5/).
