### ISSUE TITLE
Make tables in docs viewable without horizontal scrolling on Desktop

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#249]
It would be helpful if we can somehow make the tables in the documentation fully visible without having to scroll the table horizontally.  I'm attaching a screen shot of how a table currently looks:

![vip](https://cloud.githubusercontent.com/assets/355822/8174943/136a2d9a-1398-11e5-9e81-536f20efddb4.png)

**Comment by jungshadow** [comment]
@cjerdonek This is something I'm planning to tackle. I'm a little concerned that we may be pushing the boundaries of the template by using (somewhat intractable) 6-column tables. The tables are currently a problem for the generated PDF. We may eventually need to condense the tables into 5-columns (not my favorite option) or approach writing the docs in a more long-form way (e.g. [the python documentation](https://docs.python.org/3.4/library/difflib.html#difflib.SequenceMatcher.find_longest_match)).

**Comment by cjerdonek** [comment]
Personally, I think HTML tables are fine (e.g. the ones you see in the v3 docs here: http://votinginfoproject.github.io/vip-specification/ ).

In the short term, I was hoping that this issue could be addressed by a simple change (e.g. a CSS change to allow text wrapping within table cells).  In the longer term, I was going to recommend generating the docs programmatically (something I've mentioned before).  It doesn't seem like it should be necessary to edit HTML or reST tables by hand.  If the tables are generated programmatically, then things like table reformatting could be done in one place (e.g. in the script or template driving the auto-generation).

**Comment by jungshadow** [comment]
@cjerdonek Sorry, Chris. I might not have been entirely clear. Personally, I like the look of the tables, but we're breaking through the hard "physical" boundaries of the theme. When on smaller screens/devices, there just isn't enough space for the a 6-column table to exist without scrolling, especially with names like `BallotMeasureType` or `InternationalizedText` which can't wrap or be abbreviated.

The change is going to be in the CSS and will be theoretically simple, but it's still not going to solve the overall problem. In addition, it doesn't fix the PDF problem at all, but we'll cross that bridge when we come to it.

**Comment by jungshadow** [comment]
Doing a bit of experimentation, this is the result of some of the lengthier tables (_**NB:** it's hard to see, but the table expands beyond the established margins of the page_):

![table_example](https://cloud.githubusercontent.com/assets/85972/8192573/12f230b0-143d-11e5-8d78-417e2a755d0a.png)

**Comment by cjerdonek** [comment]
Okay, thanks for the clarification, @jungshadow.  Re: smaller screens, I would suggest making that a separate issue for tracking purposes.

Re: your screenshot, that looks encouraging.  Thanks for the sneak peek.  A couple suggestions: if "deprecated" in the first cell could be wrapped onto the second line, that would free up more width for the last two columns.  You could also free up more column width by abbreviating "InternationalizedText" to something like "IT", "i18n", "Int'lText", etc.

**Comment by jungshadow** [comment]
Glad you like it, @cjerdonek. I'm ok using this as a half-measure for now until we get something more scalable, long-term. I don't see the small screen as a separate issue, since we should be making sure that every element that we add to the docs is responsive on all devices. If we need to push upstream changes to the theme, I'm happy to do that.

To your second point, I was ok with removing the dot notation on elements (e.g. `ElectionAdministration.Department.VoterService`) since we're able to provide links, but I'm not comfortable with changing/abbreviating the name as I feel it could be potentially confusing.

@jdmgoogle, @pstenbjorn, et al: Feel free to weigh in here, too.

**Comment by cjerdonek** [comment]
@jungshadow I'm not saying the design shouldn't be responsive.  It's just that there are two different technical issues happening right now: (1) the table itself getting cropped, no matter how large the browser viewport is (which is what I filed this issue about), and (2) the information in the table not rewrapping to fit within small viewports.  The first issue is about needing to scroll the _table_ horizontally (and not the browser window), and the second is about needing to scroll the browser _window_ horizontally (which could be addressed by responsive design).

I was simply suggesting that these be tackled separately, because the solutions are different.  It looks like you already have a solution for the first one.

**Comment by jungshadow** [comment]
@cjerdonek That makes sense. The theme is currently responsive, but our tables are not (and are difficult to be made so given the amount of information).

For what I have, I'll submit a pull request. The content fixes (e.g. separating the name from the **[Deprecated]** bit) can be collectively handled in another issue, as well.

**Comment by jungshadow** [comment]
This is "fixed," but looks horrible on mobile. I'm going to close this issue as fixed (with the name change) and open a separate issue to deal with breakpoints. Feel free to reopen if you disagree.

**Comment by jungshadow** [comment]
Closed by #250.

**Comment by cjerdonek** [comment]
FYI, it should be easy to play around with different options (e.g. condensing columns, moving to long-form, etc) after issue #255.
