### ISSUE TITLE
Auto-generate tables in documentation

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#255]
This issue is to auto-generate the reST tables in the documentation from structured data, which is something I've suggested in the past.

I think this will open up a lot of possibilities for us.  For one, it will make the reST tables a lot easier to manage because we will be able to manage their appearance and formatting in one place.  (It is also _way_ easier to edit a YAML value than to edit a value in a reST cell!)

Some other advantages: it will reduce the amount of information we need to update by hand since everything will be more DRY.  For example, strings like "If the field is invalid or not present, the implementation is required to ignore it." can be set globally in the script that auto-generates the tables.  Auto-generating will also make it straightforward to "refactor" the tables (e.g. by adding or eliminating a new column).

A couple other things: it would open up the possibility of making alternative renderings of the tables (e.g. HTML for responsive design, etc, if the reST tables are too limiting).  Finally, it will be a lot easier to do global fixes and globally search the text values since we can just iterate over YAML data (i.e. without needing to parse anything, etc).

**Comment by cjerdonek** [comment]
I created PR #256 for this.

**Comment by cjerdonek** [comment]
To illustrate a bit more, you can see how values like "`Optional`", "`**Required**`", and "If the field is invalid or not present, then the implementation is required to ignore it." are set globally [here](https://github.com/cjerdonek/vip-specification/blob/f69a742468f381f7866c3539358a829146993490/scripts/vippy/rest.py#L75).  I noticed lots of variation in the past phrasing, a lot of which is made consistent now (though more can be done).

**Comment by cjerdonek** [comment]
I just posted PR #273 for Part 2 to address this issue.

**Comment by jdmgoogle** [comment]
Is there anything left on this particular issue which is *not* covered by #275?

**Comment by cjerdonek** [comment]
The only things I can think of are:

1. there was a request to document the Python code a little better (e.g. more docstrings), and
2. the error-related values in the YAML can be made more DRY (e.g. similar to what was done in PR #274 around error messages with the phrase, "ignore the ``parent`` element containing it").

But I would recommend creating separate issues for those rather than keeping this issue open.

**Comment by jdmgoogle** [comment]
I filed issues #279 and #280 to keep track of those. Closing this now.
