### ISSUE TITLE
Add Biography field to Candidate element

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#262]
In looking at 3.0 vs 5.0, we missed adding `Biography` to the `Candidate` element. Here's the old 3.0 description:

| Tag | Data Type | Required? | Description | Error Handling |
| --- | --- | --- | --- | --- |
| biography | String | Optional | The biography specifies the candidate's biographical information. | If the biography field is invalid the implementation is required to ignore it. |

Seems a pretty easy lift and I can crank this out fairly quickly. Any overall concerns (i.e. aside from the "just one more thing" part of it)?

**Comment by jdmgoogle** [comment]
I'm going to push this back to 5.1 for two reasons:

1. I'd like to close the door on 5.0; and
2. This isn't in 1622.2, meaning there'd be a compatibility issue.

**Comment by jdmgoogle** [comment]
Paging @jktomer: have we ever gotten bio data before? If so, did we ever use it?

**Comment by MariaDemocracyWorks** [comment]
We get it in some California counties I believe, and possibly also in Washington. I don't believe the field was ever surfaced by the API, so even where we got it, it wasn't used (or once was used because we entered into an unused party field). Is there a use case where there would be information in bio that wouldn't be covered by title or profession in person?

**Comment by jktomer** [comment]
Biography is used rarely and inconsistently.

In official California VIP feeds, it gets a very short noun phrase that is
really "occupation": "Small Business Owner," "Chief Operating Officer,"
"Santa Monica College Trustee," etc.

It was not used by any other VIP feeds in 2014, but was also used in the
Washington primaries tihs year, where the biography was a longer,
semi-structured description, as below:

"Elected Experience: Franklin County Sheriff (7 terms) 28 years (1986-2014)

Other Professional Experience: 37 years of law enforcement service,
Co-chair of the State Byrne JAG Advisory Committee, Commissioner for Law
Enforcement Accreditation Commission, Livestock Judge at County Fairs

Education: Kahlotus High School Valedictorian 1974, 1974-1977 Washington
State University studied Police Science & Administration, Seattle Police
Academy, Law Enforcement Command College, Executive Level Law Enforcement
Certification

Community Service: Youth 4-H club leader 18 years, Pasco Kiwanis Club
member 26 years, Church Life Group leader, Salvation Army Advisory Board,
Connell Christian Center Treasurer & Board member 20 years

Statement: Born, raised, educated and working in our district has uniquely
prepared me to be your Representative. Growing up and working on my
family's farm has provided me a good understanding of Agricultural issues.
Serving 37 years in law enforcement, 28 as Sheriff, I am knowledgeable of
local government issues, especially in relationship to state government. As
your Representative, my primary objective will be to ensure the state
budget funds our constitutional requirements first, utilizing available
resources, not new taxes. The private sector creates jobs, not the
government. We must limit government and let our people build our economy!"

It is not used in any unofficial datasets.

Maria is correct: we do not surface it in the civic information API,
although we do ingest it in the pipeline so it would be a small
configuration change to do so (IMO the data quality doesn't justify that
yet).

**Comment by jdmgoogle** [comment]
I'll add this to the list of things to discuss with @johnpwack w.r.t. NIST ERR v2. If it's rarely used and (even when used) has poor data quality, I'm inclined to not include it for the sake of simplicity.

**Comment by jdmgoogle** [comment]
In order to not make big changes leading up to the 2016 election, I'm going to push this back to the 5.2 milestone.

**Comment by afsmythe** [comment]
I don't believe there's a Biography attribute for Candidate (or Person) in the [1500-100 v2](https://github.com/usnistgov/ElectionResultsReporting/blob/version2/Election_Results_Reporting_UML_documentation.md#_17_0_2_4_78e0236_1389366272694_544359_2440) spec. Can we close this?

**Comment by jdmgoogle** [comment]
SGTM
