### ISSUE TITLE
Evaluate use of ContactInfo Name/AddressLine best practices

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#267]
Given the data that came in during the 2015 cycle, we should evaluate the documented best practices surrounding the use of and guidance for putting information in the `Name` field and `AddressLine` fields of `ContactInformation`.

This is a follow-up to #243.

**Comment by jdmgoogle** [comment]
I'm not sure we have enough data to evaluate this now, but refreshing the bug so it's on my radar.

**Comment by jdmgoogle** [comment]
Version 5.1 is going to be a small, targeted release. Pushing this back to version 5.2

**Comment by afsmythe** [comment]
Going to add this to the 5.3 milestone and give us some time to review what data we've collected since 5.1 release.

**Comment by jswiesner** [comment]
@afsmythe has the difference between Name and AddressLine been a point of confusion for data providers in recent years? PR #271 added additional documentation around the distinction back in 2015 to minimize the ambiguity. The outstanding question from #243 was whether or not we need to consider modifying the spec to make Name an unbounded field. If this hasn't been an issue recently, I suggest we close this issue and consider the problem solved by #271.

**Comment by afsmythe** [comment]
Agree to close. The docs are clear about how to describe a multi-line address name record (please put it on one line). Making `Name` unbounded might be a worthy cause, but we don't have any specific instances where it being bounded was a problem.
