### ISSUE TITLE
Consistent handling of polling locations, precincts, splits, and streets

### ISSUE THREAD

**Issue by pstenbjorn** [votinginfoproject/vip-specification#27]
Currently polling locations can be associated with either precincts or precinct splits and early voting sites can be associated with either precincts or localities.  Street segments can similarly be associated with both precincts and precinct splits.  In order to simplify use of the feed, a more consistent association of elements to the lowest common element would be helpful.  Specifically, if all elements could relate to a base element of precinct split, all other relationships could inherit relationships from the precinct split.

**Comment by jungshadow** [comment]
@pstenbjorn Is this issue closed?

**Comment by pstenbjorn** [comment]
@jungshadow looks like #56 should have closed this.

**Comment by jdmgoogle** [comment]
I just checked the most recent vip_spec.xsd in the vip5 branch and this looks good.
