### ISSUE TITLE
Remove sample code from RST files

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#276]
Quick question: Should we remove the sample code blocks from the documentation for the release, but add them back in at a later date? We already have the sample feed which contains all the elements (AFAICT). The current code blocks in the RST files are _mostly_ up-to-date, but several are
1. missing;
2. out-of-date; or
3. just plain wrong.

So should we remove them before release -- just to be consistent -- and add them back in for 5.1?

**Comment by jdmgoogle** [comment]
Anyone?

@jungshadow @pstenbjorn @cjerdonek @jen-tolentino etc etc?

**Comment by cjerdonek** [comment]
If there isn't enough time to check and/or correct the samples, then I'd say remove the ones that are incorrect or that you're not sure about.  It seems better than including info in the release that is known to be incorrect.

**Comment by jungshadow** [comment]
@jdmgoogle @cjerdonek Can you post a quick example of wrong and point me at a missing (_**NB:** not next to a computer right now_)? The "missing" part is a bit odd to me, since I thought we had full coverage some time ago.

**Comment by afsmythe** [comment]
We've made improvements to providing XML and CSV examples in the RST files. Going to close this and we'll handle individual inaccuracies on a case by case basis.
