### ISSUE TITLE
Improve comments in python YAML code

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#279]
Right now the python code that parses the YAML documentation and generates the RST pages is lightly commented, which makes maintaining it more difficult. This needs to be improved.

**Comment by afsmythe** [comment]
With the 2020 primaries, we didn't get to this. Punting to 5.3 and hopefully we can comment the functions sooner than later.

**Comment by jswiesner** [comment]
Considering we will all be on a trajectory of increasing busyness between now and 2024, I propose we move this up to the 6.0 milestone and take care of it this year.

**Comment by afsmythe** [comment]
Agreed.

**Comment by jswiesner** [comment]
IMO [vip.py](https://github.com/votinginfoproject/vip-specification/blob/vip52/scripts/vip.py) looks sufficiently well commented, [common.py](https://github.com/votinginfoproject/vip-specification/blob/vip52/scripts/vippy/common.py) isn't bad, and [rest.py](https://github.com/votinginfoproject/vip-specification/blob/vip52/scripts/vippy/rest.py) could probably use more comments. 

@afsmythe are you able to take a first pass at adding comments to this file? LMK if you think vip.py or common.py could use more comments as well, I could take a pass at those if needed.

**Comment by afsmythe** [comment]
Yes I can make a pass at documenting.

**Comment by jswiesner** [comment]
@afsmythe have you had a chance to take a pass at documenting? I believe this is the last step before we are ready to release 6.0.

**Comment by afsmythe** [comment]
Working on this.. Happy to contribute to a PR is something is already in progress. Should have something by first of next week.

**Comment by jswiesner** [comment]
Great, thank you! I haven't done any work on this yet, so AFAIK your changes would be the first. I'm happy to help out should there be any remaining gaps after your initial pass.

**Comment by jswiesner** [comment]
@afsmythe I think we can close this now?

**Comment by afsmythe** [comment]
Yes! Closed.
