### ISSUE TITLE
Improve off-the-shelf error message generation templates

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#280]
The error-related values in the YAML can be made more DRY (e.g. similar to what was done in PR #274 around error messages with the phrase, "ignore the parent element containing it").

**Comment by jdmgoogle** [comment]
@cjerdonek Is there any other work you'd like to do on this front?

**Comment by cjerdonek** [comment]
Yes, it's a matter of reviewing the existing error messages to see if anything else needs to be done.  I wouldn't hold anything up for it though.  It's just something that would make things easier going forward.

**Comment by jdmgoogle** [comment]
Okay, good to know. If you have time to finish this before the 26th, great, otherwise we could bump this back to 5.2. Thanks.

**Comment by jdmgoogle** [comment]
Ping @cjerdonek for a status update.
