### ISSUE TITLE
Support for city-level wildcarding

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#289]
In VIP 3.0, we supported city-level wildcarding (all people in city X vote at location Y). This was done by requiring a * in the street_name field of the non_house_address.

Consider supporting the ability to model these types of assignments in the VIP 5.1 spec.

**Comment by jdmgoogle** [comment]
Are there any objections to this feature?

**Comment by jungshadow** [comment]
@indymag @jdmgoogle Would it make sense to include another element like [IncludesAllAddresses](http://vip-specification.readthedocs.org/en/vip5/xml/elements/street_segment.html) for city-wide coverage?

**Comment by jdmgoogle** [comment]
@jungshadow That's the plan. And were you bored over the break? :)

**Comment by jungshadow** [comment]
@jdmgoogle What better way to digest an obscene excess of food than randomly chiming in on GitHub issues? ;)

**Comment by jdmgoogle** [comment]
This has been closed by #306.
