### ISSUE TITLE
Add the ability to capture national identifiers for all possible geopolitical boundaries

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#29]
In one of the recent pushes 25200a9398a03f0b9709e64bbfff62f1a80b4c5b to the vip5 branch, the common_id element was added to `electoral_district`. We should add this to other geopolitical elements as well (e.g. `locality`, `precinct`, et al), understanding that VIP may need to communicate with the [OCDIDs](http://opencivicdata.readthedocs.org/en/latest/ocdids.html) community around any issues we have with conflicting official data.

**Comment by jdmgoogle** [comment]
The external_identifier approach should fix this.
