### ISSUE TITLE
Specify a convention for candidate ordering and office ordering for CandidateSelection and CandidateContest

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#291]
A CandidateSelection, can list multiple candidates in case they are part of a ticket.  There should be a convention specified to say that they must be in the same order as the officeIds in the CandidateContest that they are associated with.    These candidates within each selection should be in the same order (e.g. c1[0] = 'Obama', c1[1] = 'Biden', c2[0] = 'Romney', c2[1] = 'Ryan').

This order should also be the same as the officeIds specified in CandidateContest element.

This seems much simpler than trying to explicitly describe the candidate->office mapping per ticket/selection.

**Comment by johnpwack** [comment]
Hi all,

In the NIST spec, we mention this, but I suspect I could make it more
clear.

For the CandidateContest element, I write:
"For cases when the contest is associated with multiple offices, e.g., if
Governor and Lt. Governor are both separate offices, it is expected that
the generating application will list the multiple references to <Office>
according to any ordering scheme in place."

For the CandidateSelection element, I write:
"When multiple candidates are referenced for a ticket and the ordering of
the candidates is important to preserve, it is expected that the generating
application will list the occurrences of *<CandidateId>* according to the
ordering scheme in place."

Looking at this now, I can see I was attempting to be general, but it comes
at a cost to this specific issue, which is keeping the order of the
CandidateId elements the same as the order of OfficeId elements.  I will
re-write the documentation to be more clear - I'll get back in touch with
some new language hopefully later today and I'd be appreciative of any
comments on it.

Cheers, John



*---*

*John P. Wack*

johnpwack@gmail.com

301.640.6626 - cell

301.975.3411 - office

**Comment by jdmgoogle** [comment]
I will update the best practices document and the sample feed to make this explicit.

**Comment by jdmgoogle** [comment]
Closed by #309.
