### ISSUE TITLE
Update HISTORY.md just prior to the 5.2 release

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#295]
Make sure the [changelog](HISTORY.md) is up-to-date prior to release.

**Comment by afsmythe** [comment]
5.2 changelog summarized in this PR https://github.com/votinginfoproject/vip-specification/pull/407

**Comment by afsmythe** [comment]
`HISTORY.md` updated: https://github.com/votinginfoproject/vip-specification/blob/vip52/HISTORY.md
