### ISSUE TITLE
Links to projects implementing this specification

### ISSUE THREAD

**Issue by bcipolli** [votinginfoproject/vip-specification#297]
It would be great to aggregate, in the documentation, open-source projects that implement this specification. Having this spec is great, but knowing what tools have been developed to support the spec is even better :)

For example:
- Are there **back-end apps** (e.g. Django apps or Ruby gems) that implement the database schema detailed here and expose XML/CSV outputs?
- Are there **open-source clients** that consume feeds per this spec and validate them?

Full disclosure: 
I'm looking at whether using the vip-specification as part of an "open disclosure" (scraping, storing, and visualizing campaign finance data) project could set the app up to interact with related apps (finding ballot measures, election dates, voting locations, etc).

I'm interested in discussing what apps exist, and whether y'all would be interested in adding them to documentation here. Thanks!

**Comment by jdmgoogle** [comment]
Most of the users of this spec are actually users of the [Civic Information API](https://developers.google.com/civic-information/?hl=en), which is where Google takes the data and re-exports it via the API. As for open-source implementations of data producers or consumers ... paging @pstenbjorn @nomadaisy @jungshadow @cjerdonek and @MariaDemocracyWorks to see if they know of any/can contribute.

**Comment by jungshadow** [comment]
Everything @jdmgoogle says. There are projects here that deal with the processing of feeds. It might be helpful to take a look at the [data-processor](https://github.com/votinginfoproject/data-processor) application. @nomadaisy, @MariaDemocracyWorks, or @acohen84 are much more equipped to talk about this in greater detail. @cjerdonek also may have something cooking :)

**Comment by jungshadow** [comment]
To add to the above, if you want to get a local version of the processor running, [data-suite](https://github.com/votinginfoproject/data-suite) may be more useful. Good point about updating the docs to show uses in the wild.

**Comment by jswiesner** [comment]
@afsmythe What do you think about adding a list of VIP publishers to the documentation to address this?

**Comment by jswiesner** [comment]
This is addressed by #417. Can we close the issue?

**Comment by afsmythe** [comment]
Fine with me.

**Comment by jswiesner** [comment]
Closing this as a result of #417.
