### ISSUE TITLE
Sync VIP 5.1 to latest NIST standard

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#305]
I have a copy of v50 of the NIST Election Results Reporting spec. There are a few changes which need to be incorporated into v5.1 of VIP, including an updated `ContactInformation` which includes `Directions` and `LatLng` elements. This will be a tracking bug to make sure we stay on top of this.

**Comment by jdmgoogle** [comment]
Just confirmed that the [final official release of the NIST standard](http://www.nist.gov/itl/vote/election-results.cfm) is v50, so we can close this out.

**Comment by jungshadow** [comment]
![The Dude rocking out](http://bukk.it/creedence.gif)
