### ISSUE TITLE
Add clarifications for Schedule overlaps within a HoursOpen element

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#314]
I started writing this up directly, but rather I'll go through the correct process for a non-contributor and open an issue.  
https://github.com/votinginfoproject/vip-specification/pull/313/files

The spec should add some guidance about HoursOpen elements.  The schedule elements within a single HoursOpen shouldn't overlap with each other.  The range created by StartDate to EndDate should be mutually exclusive between schedules within the same element.

I don't think the original intent was to allow any overlaps, and if that's the case, I suggest adding this clarification to 5.1 itself.  If the intent was to allow overlapping, I think its going to be misused and suggest a simplification in 5.2.  Either way, 5.1 deserves some clarification.

Finally, StartDate and EndDate in Schedule should be noted as "inclusive" in the description of these attributes to avoid any ambiguity.

**Comment by jdmgoogle** [comment]
I'm creating a 5.1.1 release target just to catch small stuff like this.

**Comment by jdmgoogle** [comment]
@indymag: The original PR looks good. Please follow the instructions in the CONTRIBUTING document to create a full PR that updates the YAML and the RST files, and we can merge it into the new vip511 branch.

**Comment by jdmgoogle** [comment]
I went ahead and took care of this myself. I accidentally [made a commit](https://github.com/votinginfoproject/vip-specification/commit/d7f8ae3fd89d820b79f507c123fa1f86a24ad003) directly to the vip511 branch instead of going through the PR process. Paging @indymag and @pstenbjorn to yell me about that (and hopefully retroactively okay the change).
