### ISSUE TITLE
Incorrect documentation for SequenceOrder

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#315]
IIUC BallotSelectionBase should have a SequenceOrder that has the order that the selection appears within a contest.
http://vip-specification.readthedocs.io/en/vip5/xml/elements/ballot_selection_base.html

Similarly, ContestBase SequenceOrder's description should be updated.  IIUC, It is the order in which the contest is listed on the ballot (and has nothing to do with the selections/candidates).  While this is definitely not a preferable way to specify such a thing (OrderedContest is far superior), the documentation should accurately reflect its intent.

http://vip-specification.readthedocs.io/en/vip5/xml/elements/contest_base.html

**Comment by cjerdonek** [comment]
> IIUC BallotSelectionBase should have a SequenceOrder that has the order that the selection appears within a contest.

Here, isn't it the case that a given "BallotSelectionBase" can appear in different locations within the ordering depending on ballot rotation, etc? For example, the [OrderedContest](http://vip-specification.readthedocs.io/en/vip5/xml/elements/ordered_contest.html) docs say, "If no OrderedBallotSelectionId elements are present, the presumed order of the selection will be the order of BallotSelectionBase-extended elements referenced by the underlying ContestBase-extended elements."

And isn't there a similar issue for contests?

**Comment by jdmgoogle** [comment]
Fixed by #316.
