### ISSUE TITLE
An "AnnotatedURI" type for //ContactInformation/Uri

### ISSUE THREAD

**Issue by rsimoes** [votinginfoproject/vip-specification#317]
It would be helpful if `Uri`s in `ContactInformation` had specified an annotation attribute (just like `AnnotatedString`) that could be used for indicating what kind of resource is to be found at the address: social media, campaign website, etc. E.g.,

```xml
<Uri annotation="facebook">https://www.facebook.com/DonaldTrump</Uri>
```

**Comment by jdmgoogle** [comment]
Closed by #320
