### ISSUE TITLE
VipObject's schemaVersion attribute is still fixed at "5.1" in the 5.1.1 release 

### ISSUE THREAD

**Issue by rsimoes** [votinginfoproject/vip-specification#323]
Would "5.001001" be passable?

**Comment by jdmgoogle** [comment]
The changes were small enough (mostly documentation updates, plus one backwards-compatible change) that I felt it wasn't necessary to bump the required version number.

I'm open to suggestions or feedback if people feel this will be an actual problem, though.

**Comment by jdmgoogle** [comment]
Proactively declaring this issue obsolete/won't-fix since we're about to release 5.2.
