### ISSUE TITLE
Possibly move IsPartisan from Office to CandidateContest

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#329]
This change will need to be reflected in the NIST spec, too.

See

http://www.nlc.org/build-skills-and-networks/resources/cities-101/city-officials/partisan-vs-nonpartisan-elections

**Comment by JDziurlaj** [comment]
I would note that NIST 1500-100 v2 keeps `IsPartisan` in the `Office` class. In the absence of an another argument, I would advocate for leaving it in `Office`. One reason would be for the production of *elected official* lists, where a person record may have a partisan affiliation, but it needs to be omitted in the body of the report.

**Comment by jdmgoogle** [comment]
I think v2 got it wrong, but in the spirit of compatibility I'm fine dropping this. But **v3** will surely fix this. :)

Speak now or I'll just close this one out.

**Comment by afsmythe** [comment]
Can we close this?

**Comment by jdmgoogle** [comment]
Moving it to v6.0.

**Comment by JDziurlaj** [comment]
I am not in favor of moving this element. The `Office` can be partisan and the contest having partisan designations is a downstream impact of that.

**Comment by jdmgoogle** [comment]
@JDziurlaj Could you define what you mean by the office being partisan beyond it being elected through a partisan process?

**Comment by JDziurlaj** [comment]
Offices represent slots to which candidates may be elected. While some may see the "partisaness" as a byproduct of the electoral process alone, I believe it also influences how those elected officials are expected to behave, i.e. in a less partisan fashion.

**Comment by jdmgoogle** [comment]
Thanks.

I think what I'm trying to get at here, though, is that it's relatively straightforward to tell if a contest is partisan (e.g., party affiliation is listed on the ballot, candidates have the option to go through a partisan primary to get on the ballot, etc), but slightly less so for offices.

IOW, what objective criteria could someone use to determine the "partisan-ness" of an office and whether there were partisan expectations?

**Comment by JDziurlaj** [comment]
There must be some entity that stores facts about how an election to office is to be conducted, whenever that office is up. I am conflating all that in the entity `Office`. The issue with putting it in `Contest` is that a contest is always a particular, i.e. a contest IN a particular election. 
I think the expectations on the conduct of officials elected via a non-partisan process are culturally defined.

**Comment by jdmgoogle** [comment]
Well .... I still think this is wrong, but this wrong-ness appears to be codified in NIST 1500-100v2, so we can maintain this wrong-ness in VIP v6, too. 😄 

Unless there are objections? @jswiesner? @cjerdonek? @afsmythe?

**Comment by afsmythe** [comment]
Maybe for some background around the initial thinking of v5, what is a practical difference between `Contest.PrimaryPartyIds` and `Contest.IsPartisan`? Are these fields supposed to complement one another? Do they describe different aspects of a ballot item?

**Comment by jdmgoogle** [comment]
Thoughts, @JDziurlaj @afsmythe

**Comment by JDziurlaj** [comment]
For use-cases for 1500-100, we need to consider State EMS to Local EMS scenarios (as well as the converse). The `Office` exists independently of an `Election` object in the 1500-100 feed. This `IsPartisan` flag could be used to inform the creation of contests in that downstream system. I would add that in 1500-100 `Election` is a particular, as `StartDate` and `EndDate` are both required elements.

**Comment by afsmythe** [comment]
I'm failing to understand the benefit of moving `IsPartisan` to `Office`. And to this point

>It's not as if the Office element is durable, living on from feed to feed. 

Shouldn't `Office` be durable, even it isn't in practical applications of VIP feeds? An office is a fairly stable entity. 

It seems an office _could_ be partisan (but I don't know what types of offices actually are, is there  a practical example?). Of course the _path to the office_ is partisan when there is a primary party contest, and we handle that presently with `CandidateContest.PrimaryPartyIds`. So how will that current practice be affected if `IsPartisan` is moved?

**Comment by jswiesner** [comment]
@afsmythe raises a good point about CandidateContest.PrimaryPartyIds. The presence of one or more CandidateContest.PrimaryPartyIds should mean the same thing as CandidateContest.IsPartisan = True. 

Do you all agree with that? @afsmythe @jdmgoogle @JDziurlaj. If so, I suggest we close this.
