### ISSUE TITLE
PollingLocation.AddressLine Location Name Handling

### ISSUE THREAD

**Issue by MariaBianchi** [votinginfoproject/vip-specification#330]
A mistake a state made in creating the XML highlighted for me that there's no longer a name element in the polling location object. This handling worries me a little, because Location Name is so useful to voters.
Also, currently the VIP tools don't pass polling location names through to the maps geocoder for mapping, but if it's included as an address line, we won't have that option. Does this seem like a cause for concern to others?

At the very least, it seems like we'll want to update the documentation to make clear that location name needs to be included as an "AddressLine", since the description right now doesn't make that clear.

**Comment by jdmgoogle** [comment]
Closed by #334.
