### ISSUE TITLE
Add an optional ContactInformation subelement to Candidate

### ISSUE THREAD

**Issue by rsimoes** [votinginfoproject/vip-specification#331]
It feels semantically incorrect to be placing campaign contact information inside a Person element--especially in the few cases where two Candidate elements have a common PersonId. Could the Candidate or CandidateSelection element also have an optional ContactInformation subelement?

**Comment by jdmgoogle** [comment]
That makes sense. This was an element we pulled in from the NIST 1500-100 spec, though, so I'm not sure we can fix it here. The best I can recommend is to use multiple ContactInformation elements with a Person and put a note linking them to a specific Candidate object.

**Comment by jdmgoogle** [comment]
Similar to other VIP/NIST overlap element issues, I'm willing to extend `Candidate` objects to include an optional `ContactInformation` element.

**Comment by jdmgoogle** [comment]
Closed by #342.
