### ISSUE TITLE
Add IsWriteIn to Party object

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#332]
Add a boolean `IsWriteIn` to the `Party` object. This is needed because some candidates are allowed to enter free-form Party names to identify themselves in some instances (looking at you, Washington and Wisconsin) and those names may not correspond to a real political party.

The rule of thumb for deciding if a Party is a write-in party or not is: is this a political party which is recognized by an election administration in this city/county/state/country? If yes, then the value should be false. If not, then this is a write-in party which may entirely be the creation of one candidate and feed consumers shouldn't attempt to ready anything else into the party name or information.

If this field is absent then it should be treated as `false`.

**Comment by pstenbjorn** [comment]
@jdmgoogle sounds confusing, but I believe I followed and LGTM

**Comment by jdmgoogle** [comment]
@pstenbjorn Some states (e.g., WI) allow candidates to enter the name of the party they want shown next to them on the ballot. This party name doesn't have to line up with any registered party, and can in fact be whatever (within reason) the candidate wants to have next to their name. This flag is basically a way to signal that a feed consumer shouldn't expect this political party to show up ... well ... anywhere else.

**Comment by indymag** [comment]
LGTM

**Comment by jdmgoogle** [comment]
Closed by #333.
