### ISSUE TITLE
Questions on //Party/IsWriteIn

### ISSUE THREAD

**Issue by rsimoes** [votinginfoproject/vip-specification#335]
- Should there be a separate Party with the same Name as a non-write-in Party when IsWriteIn is true but the written-in Name is identical to the existing, non-write-in Party's?

- If two candidates in very distant electoral districts write in the same party name, should those Candidates (and potentially no one else) have the same PartyId?

**Comment by jdmgoogle** [comment]
Paging @indymag and @jktomer to weigh in.

**Comment by indymag** [comment]
I don't have strong feelings about this, but my recommendation:
- If the candidate is writing in their party, they should always have a separate party that indicates IsWriteIn.  It is the only way proposed to capture the information that the candidate self-selected the party w/o any formal affiliation.

- If two candidates both pick the same party name, it is possibly for arbitrary reasons.  By default, we should create one Party element per self-affiliated candidate.  There is no need for the data to pre-reconcile in this instance that I can think of.

**Comment by jdmgoogle** [comment]
@rsimoes Does this answer your question?

@indymag @jktomer Thoughts?

**Comment by rsimoes** [comment]
Looks good to me. Thanks for the response!
