### ISSUE TITLE
Type child element for Locality should be optional

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#336]
For a Locality, the Type element is listed as optional in the documentation, but is required in the XSD.  It should probably be optional.

http://vip-specification.readthedocs.io/en/release/built_rst/xml/elements/locality.html
https://github.com/votinginfoproject/vip-specification/blob/vip52/vip_spec.xsd#L444

**Comment by jdmgoogle** [comment]
@indymag Could you explain a bit more about why you think Type should be optional?

**Comment by indymag** [comment]
It isn't really needed for our use case.  We are linking Locality elements to Polling Locations for early voting.  Those locality elements are referenced by external identifiers to their OCD Division ID.    Type doesn't add value for our use case.

Additionally, the documentation says its optional though.  So its an easy mistake to make.  

Is there a reason why Type was required?

**Comment by jdmgoogle** [comment]
It was required in the [3.0 spec](https://github.com/votinginfoproject/vip-specification/blob/v3-archive/vip_spec_v3.0.xsd), so that probably just carried forward. If this is legitimately causing an issue then we can ditch it.

**Comment by indymag** [comment]
I think we should relax for 5.2 if it isn't really needed.  In the meantime, I'll see if a workaround is feasible.
