### ISSUE TITLE
Add ExternalIdentifiers to Person element

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#340]
It is often useful to indicate that two candidates are the same Person, just running for multiple offices.  This is handled by the spec well (Person elements can be shared when linked to Candidate elements).  Where this falls down is external identifiers for a person.  The person likely has a single Wikipedia page.  It'd be good to indicate this on the Person element and not repeat it on the Candidate Element.   Additionally, this opens up ExternalIdentifiers for non-candidates.

**Comment by jdmgoogle** [comment]
Fixed by #341.
