### ISSUE TITLE
Update documentation to reflect changes to data processor

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#349]
Recently, the [data processor](https://github.com/votinginfoproject/data-processor) merged [a pull request](https://github.com/votinginfoproject/data-processor/pull/227) that _technically_ violates the specification. I use the word _technically_ because it may be worth considering [this section](http://vip-specification.readthedocs.io/en/release/xml.html#naming-convention) an artifact of a different time (i.e. when feeds were harvested directly from state servers over HTTP or FTP, and the file name, when it carried a timestamp, was more meaningful).

Only considering the spec be updated, I see three choices here:
1. The spec changes to account for the new changes to the data processor.
2. The spec changes to include language that is suggestive rather than imperative (i.e. _may_ as opposed to _should_).
3. The spec changes to exclude the section entirely, if dictating filenames is impractical (_**NB:** there are some niceties built into the filename&mdash;especially in the new data processor format&mdash;that help determine the contents at a glance...assuming the name isn't mislabeled_).

Personally, I appreciate rigidity where it's possible and relatively simple for any party to control. Since the project is still based on file exchange, I find the naming convention useful. Currently, most&mdash;if not all&mdash;of the feeds are processed by the data processor, but, assuming states start centralizing their localities' data, it may be advantageous to keep the naming convention.

Clearly, I don't have a horse in this race, but I figured I'd bring it to attention, since I noticed it. Happy to submit a pull request to change the documentation, if needed/helpful.

**Comment by indymag** [comment]
Thanks for the helpful note!

I support updating the spec to recommend the new naming convention (#1).
It is very useful in this domain to have a convention.  In OASIS-speak,
this would be a SHOULD (not a MUST or MAY).

**Comment by jdmgoogle** [comment]
To clarify, is the proposed new naming convention

vipFeed-${FIPS}-${JURISDICTION_NAME}-${ELECTION_DATE}.{zip|xml}?

For example, what's the new filename for a (hypothetical) VIP feed that would currently be named:

vipFeed-22095-2016-11-08.zip

?

**Comment by jungshadow** [comment]
@indymag Sounds good and agree. Given a bit of clarification (more on that below), happy to submit the pull request for the change.

@jdmgoogle The template looks correct to me, though I think they're not camel-casing the "vipFeed" prefix anymore (i.e. vipfeed). The subjurisdiction example was the case I wasn't clear on. I was looking for some confirmation from @tie-rack on [my last comment on the pull request](https://github.com/votinginfoproject/data-processor/pull/227#discussion_r82448864):

> To provide a quick example for my edification, the zip filename for a Maricopa County, AZ feed for the general election would be `vipFeed-04013-AZ-2016-11-08.zip`?

If I'm reading the existing code correctly, it currently only adds the state. It feels a little inconsistent, but I can see how always using the jurisdiction name, regardless of level, might make for some lengthy filenames (e.g. `vipfeed-1759000-peoria_city-2016-11-08.zip`), which leads to some additional complicated questions (e.g. do we separate multi-word place names by underscores; are place designation like "city" or "county" dropped; when is a designation like "city" also part of the name; etc...).

All that said, it may just be simpler/easier to stick with the state abbreviation :)

**Comment by jdmgoogle** [comment]
Again, I'll leave the specifics up to @indymag and @jktomer since the Google pipeline is more their things these days. My only observation/suggestion would be to change the formatting to

vipfeed-${FIPS}-${ELECTION_DATE}-${STATE}-${LOCAL}.{xml|zip}

If there are dashes or other odds characters in the filename, I suspect that this pattern will be easier to capture via regexps. Plus this file listing:

vipfeed-12-2016-03-01-Florida.zip
vipfeed-12-2016-11-08-Florida.zip
vipfeed-37-2016-11-08-North_Carolina.zip
vipfeed-51-2016-03-01-Virginia.zip
vipfeed-51-2016-11-08-Virginia.zip

would be easier to scan than

vipfeed-12-Florida-2016-03-01.zip
vipfeed-12-Florida-2016-11-08.zip
vipfeed-37-North_Carolina-2016-11-08.zip
vipfeed-51-Virginia-2016-03-01.zip
vipfeed-51-Virginia-2016-11-08.zip

But that's just my $0.02.

**Comment by tie-rack** [comment]
To be frank, I don't understand why this is getting so much attention. The names of the files aren't semantically important to either VIP's processing of data or Google's ingestion of it. The files we receive can be named literally anything and the files we provide to Google can be named literally anything.

That doc says "should" and that's good enough for people providing us data, but doesn't need to be iron clad about what we name files for our own use.

**Comment by jungshadow** [comment]
> ... My only observation/suggestion would be to change the formatting to
>
> `vipfeed-${FIPS}-${ELECTION_DATE}-${STATE}-${LOCAL}.{xml|zip}`

That looks good to me.

> To be frank, I don't understand why this is getting so much attention. The names of the files aren't semantically important to either VIP's processing of data or Google's ingestion of it. The files we receive can be named literally anything and the files we provide to Google can be named literally anything.

I can appreciate your view on this, @tie-rack. The file naming convention has always been a part of the standard. While that sounds like a shibboleth, in reading the reason behind the recent change to the data-processor, you've realized that there is some utility for human data processors, something I think holds true for people both inside and outside of the project. Now that I'm on the outside, the naming convention is definitely useful to me. Beyond the human processing/validation, Democracy Works may not be the only organization creating a VIP data processor or implementing the VIP standard in some way. In short, I think the naming convention still has use.

**Comment by indymag** [comment]
+1.  The convention is useful for increasing the debuggability of the
overall system.  It's a "should" because something less informative would
definitely slow down troubleshooting.

**Comment by jdmgoogle** [comment]
Closed by #352.
