### ISSUE TITLE
Provide a way to provide structured addresses for Polling Locations

### ISSUE THREAD

**Issue by indymag** [votinginfoproject/vip-specification#351]
We moved from structured to unstructured addresses for polling locations in the transition from 3.0 to 5.1.  I'm uncertain if this was a win.  We had numerous problems in interpreting unstructured addresses.  Additionally, it added a bit of unpredictability to the system.  It wasn't always clear to the data provider what needed to be done in order to get an address through the system.  A structured address adds a degree of predictability that shouldn't be discounted.

My preference would be to move to fully structured addresses for VIP 5.2 (don't allow unstructured).

**Comment by afsmythe** [comment]
Support of unstructured polling location addresses removes the requirement to parse out the address fields in to structured columns. This on the surface would seem to simplify the data provider's work to generate a polling location list. With 5.1 the provider only needed to provide a polling location name and unstructured address to identify the polling place.

**Comment by afsmythe** [comment]
For the 5.2 revision we're hoping to support structured or unstructured polling location addresses. Supporting either will allow 5.1 states to continue VIP submissions without upgrading while new upgrades to 5.2 can take advantage of a structured address type. 

From a high level, it sounds like we'll need to incorporate a "structured address" complexType in to the `PollingLocation` element and specify in the XSD that `PollingLocation` requires either the new structured address type or a value for the unstructured `PollingLocation.AddressLine`, which is presently required. If both are provided, the structured address should take precedence in implementation. 

Does this summary sound correct? And should other objects in the spec which currently use non-structured addresses (e.g. `ContactInformation`) also incorporate the new structured address complexType?

**Comment by afsmythe** [comment]
Does the [3.0 `simpleAddressType`](https://github.com/votinginfoproject/vip-specification/blob/6f931f9e53725c5fa0179326552d5d75122becef/vip_spec_v3.0.xsd#L336) incorporate all the necessary elements?

**Comment by jdmgoogle** [comment]
I think it does incorporate the necessary elements. I'd propose to use xs:choice in order to make sure that providers use either AddressLine or a simple address (componentized) but not both.

**Comment by afsmythe** [comment]
The `xs:choice` XSD option is included for these two items in the `PollingLocation` object: https://github.com/votinginfoproject/vip-specification/blob/ba3eaa2a0dd359ea663c317f21697a3dfd29292a/vip_spec.xsd#L537

**Comment by JDziurlaj** [comment]
As an FYI, the tooling used to produce the NIST CDF is not capable of generating xsd:choice structures. If compatibility with the NIST CDF is a long term goal, I would suggest using xsi:type structures instead.

**Comment by jdmgoogle** [comment]
Understood. However _that_ change wouldn't be compatible with the libraries we're using to ingest data, at least not in a backwards-compatible way. If we did go that route, we'd likely have to bump the version number to 6.0, since a core part of the spec would no longer be backwards-compatible.

**Comment by jdmgoogle** [comment]
@afsmythe Could you put together a PR that implements the xsd:choice option for structured polling location addresses?

@JDziurlaj The other aspect is that polling location addresses aren't part of the NIST spec, so there wouldn't be (new) compatibility issues between VIP 5.x and NIST 1500-100.

**Comment by JDziurlaj** [comment]
@jdmgoogle polling places are supported in the 1500-100 format. They are `GpUnits` of `Type`= `polling-place`. WI is using this feature. At this point, I have no opinion on the best path forward.

**Comment by jdmgoogle** [comment]
@afsmythe I was hoping to isolate this change as opposed to having it be in a grab-bag of changes. If that's too much or you feel the existing PR is close enough then we can move forward with the existing PR.

@JDziurlaj Wisconsin has found a way to create a full VIP5-equivalent feed in NIST 1500-100? I.e., it links addresses to precincts and precincts to polling locations?

**Comment by afsmythe** [comment]
I can clean up the PR. How would you like the changes to be made? Within 1 PR inclusive of all the 5.2 spec updates, or having each spec change (i.e. XSD change) a part of its own exclusive PR?

**Comment by afsmythe** [comment]
@jdmgoogle I can structure the PRs as suggested here: https://github.com/votinginfoproject/vip-specification/blob/vip52/CONTRIBUTING.md#pull-requests

With this being a minor revision I thought we'd want all the changes in the a single PR. But I understand the value of having each spec change in its own PR for cleanliness, ease of review and approval.

**Comment by jdmgoogle** [comment]
Thanks. I think the content is all pretty much there, but being able to discuss and track each change in isolation makes it easier to understand and audit.

**Comment by afsmythe** [comment]
This PR https://github.com/votinginfoproject/vip-specification/pull/387 reintroduces structured polling locations to the specification (revision 5.2).
