### ISSUE TITLE
How to denote a "Special" election?

### ISSUE THREAD

**Issue by gordonje** [votinginfoproject/vip-specification#353]
ElectionType on Election is described as where the highest controlling authority is denoted (e.g., federal, state, county, city, town). Your docs also recommend combining unrelated contests that occur on the same day under one Election object.

So where could we denote that an election is a special election (i.e., occurring as a result of an unexpected vacancy in an office)? A special election might also be called to put a slate of ballot measures to the voters. At least that has happened in California once.

I could sorta see this going into BallotName on ContestBase. But maybe a more clearly defined field is there/should be there?

Great project, really important.

**Comment by gordonje** [comment]
Just looking back at the repo's history, it appears as though the Content element previously included a "Special" boolean field. Actually, your [xml](https://github.com/votinginfoproject/vip-specification/blob/vip52/examples/contest.xml) and [txt](https://github.com/votinginfoproject/vip-specification/blob/vip52/examples/contest.txt) examples both still include this field. Would we consider bringing this back? Or maybe someone could explain the rationale for getting read of it?

**Comment by jdmgoogle** [comment]
Thanks for the feedback.

The examples/ directory is part of the CSV documentation (I believe?) and at this point either needs to be updated to be in line with 5.x or it needs to be nuked. (Accordingly, paging @nomadaisy and @cjerdonek)

Regarding `ElectionType`, in the 5.2 spec that is an `InternationalizedText` field in the `VipObject` meaning that it can be set via free-form `InternationalizedText`. E.g.,

```
<Election>
  <ElectionType>
    <Text language="en">Special</Text>
    <Text language="fr">Spécial</Text>
    <Text language="es">Especial</Text>
  </ElectionType>
</Election>
```

**Comment by gordonje** [comment]
Oh right (duh). Thanks for the response!
