### ISSUE TITLE
v5.1.2-release tag seems wrong

### ISSUE THREAD

**Issue by sduckett** [votinginfoproject/vip-specification#356]
If I look at the v5.1.2-release tag, I'll find a spec [that says it's 5.1.1](https://github.com/votinginfoproject/vip-specification/blob/v5.1.2-release/vip_spec.xsd). 

[I bumped the version](https://github.com/votinginfoproject/vip-specification/commit/26d3f5e097ef99fdbde124ad6248cbc7b8f0a984) but I'd like to fix the tag _and_ use the same name - the insane thing, [according to the manual](https://git-scm.com/docs/git-tag#_discussion) - but anyone who's fetched that tag will be inconvenienced. Does this seem bearable, or is there perhaps a smoother approach?

**Comment by sduckett** [comment]
Howdy @jdmgoogle, I merged #352 yesterday; do you want to update the tag or should I?

**Comment by jdmgoogle** [comment]
@sduckett Feel free to update the tag and close out the 5.1.2 milestone. :)

**Comment by sduckett** [comment]
OK, I've pushed a new tag.
