### ISSUE TITLE
Description of Contest object's number_voting_for is same as number_elected

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#36]
In the current web site documentation (Version 3.0), the description of the [Contest](http://votinginfoproject.github.io/vip-specification/#contestitems) object's `number_voting_for` tag is the same as the description for `number_elected`.

The description for `number_voting_for` reads--

> The `number_voting_for` field specifies the number of candidates elected to the office in this contest.

If this is supposed to be the same, a clarifying note would help.

**Comment by pkoms** [comment]
I believe number_voting_for and number_elected should be different. Consider a case like Minneapolis municipal elections: voters vote for multiple (ranked) candidates for mayor, but there's only one mayor.

**Comment by pkoms** [comment]
(This seems to intersect with #38).

**Comment by cjerdonek** [comment]
Yes, the idea of "number of candidates the voter is allowed to choose" is separate from the idea of "number of winners."  This also comes into play for "vote for N" races, [limited voting](http://en.wikipedia.org/wiki/Limited_voting) (where voters can choose only one candidate even though multiple can win), and cumulative voting.  For cumulative voting though (and to some extent RCV), "number voting for" may be a misnomer.  In cumulative voting, the voter can cast multiple votes for the same candidate.  Referencing ballot "marks" or "choices" in the name might be better if this were going to apply beyond vote-for-N to RCV and cumulative.

**Comment by jungshadow** [comment]
@pkoms @cjerdonek This is all great info, but I might advise suspending any ballot-related discussion until @jdmgoogle incorporates the 1622.2 ballot models. Mostly to save energy. I'm sure we'll have more to discuss when the new models are incorporated :)

**Comment by jdmgoogle** [comment]
Indeed. Please see #43 and we can hammer out the discussion there.

**Comment by jdmgoogle** [comment]
Fixed with the adoption of the 1622.2 schema elements.
