### ISSUE TITLE
[Discussion] Add LeaderPersonIds to Party

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#364]
It may be useful to know the leader of a political party (for some definition of "leader").

This is to be compatible with usnistgov/Voting#9

**Comment by jswiesner** [comment]
This looks like a reasonable and straightforward addition to 6.0. Thoughts on moving this to the 6.0 milestone?

**Comment by jdmgoogle** [comment]
I support this.

Thoughts, @afsmythe et al?

**Comment by afsmythe** [comment]
Sounds good!

**Comment by jswiesner** [comment]
Looks like we're aligned on this feature. @afsmythe could you move to the 6.0 milestone (I don't have permission)?

**Comment by jswiesner** [comment]
Implemented with:
- d029e95336cf483423ca08c082d23051a919055c

Documented with:
- b71d32fc94466cba28be46e21ca1eb0844828c90
- 8bafbaed12705bccf1275830415842d50df6e0e4

Can we close this issue now?

**Comment by afsmythe** [comment]
Fine with me.

**Comment by jswiesner** [comment]
Closing this issue as a result of https://github.com/votinginfoproject/vip-specification/issues/364#issuecomment-982266453.
