### ISSUE TITLE
Improve documentation around non-traditional voting sites and methods

### ISSUE THREAD

**Issue by afsmythe** [votinginfoproject/vip-specification#365]
Issue created to serve as a placeholder for a future PR aimed at improving 5.1 documentation around vote centers, early voting, and mail-in balloting. Any PR should improve information for the following and should highlight relevant elements/fields. Describing scenarios for linking to `Precinct` and/or `Locality` should also be included. 

- Vote centers
- Early voting
- Vote by mail

We presently have a decentralized record for each of these ([locality](http://vip-specification.readthedocs.io/en/vip52/built_rst/xml/elements/locality.html), [polling location](http://vip-specification.readthedocs.io/en/vip52/built_rst/xml/elements/polling_location.html)). Considering the differences from 3.0 standard, having a more descriptive FAQ-esque record of these non-traditional polling practices will assist states with implementing 5.1.

**Comment by jdmgoogle** [comment]
While I'm going through the backlog of issues, what's the relative priority of this?

**Comment by jdmgoogle** [comment]
What's the status of this request?

**Comment by afsmythe** [comment]
Let's punt on this since it seems like a candidate for an FAQ type of entry.

**Comment by afsmythe** [comment]
Vote centers and early voting is well documented. Closing this Issue and tracking concerns around Vote By Mail expansion here: https://github.com/votinginfoproject/vip-specification/issues/400
