### ISSUE TITLE
Add field to ElectionAdministration object to associate ballot tracking URL

### ISSUE THREAD

**Issue by afsmythe** [votinginfoproject/vip-specification#367]
Presently, the `ElectionAdministration` object provides for URL's of various purposes to be associated with the administration of that district, e.g. Absentee voting (AbsenteeUri), registration (AmIRegisteredUri), elections (ElectionsUri) etc. Some elections offices have additional tools made available to mail-in voters allowing the voter to track their absentee ballot as it moves through the postal service, i.e. [Denver's Ballot Trace](https://www.denvergov.org/content/denvergov/en/denver-elections-divison/voter-election-information/ballot-trace.html), among others. Adding a field to the VIP specification (say, BallotTrackUri) to handle this specific type of URL would further make the 5.1 specification attractive to states providing such tools. 

P.S. pinging @MariaBianchi - feel free to add additional info here.

**Comment by jungshadow** [comment]
@afsmythe I may be missing something, but I'm a bit confused here. Are you referring to the [`ElectionAdministration` element](https://vip-specification.readthedocs.io/en/release/built_rst/xml/elements/election_administration.html) (not `ElectoralDistrict`)?

**Comment by afsmythe** [comment]
Woops. Yes, @jungshadow. Thanks for catching! I've updated the original description.

**Comment by jungshadow** [comment]
Awesome! Not that it matters, but sounds like a good idea to me. In general (and I know it's not easy), it would be great if the existing links were more consistently populated.

**Comment by jdmgoogle** [comment]
Do we have any idea:

1. How many states or counties have something like this in place?
2. How many people use such a feature?
3. Where this data would get surfaced?

I support the idea and it makes sense for the spec. The question is if this should go into a 5.1.x release (maybe ready in time for this cycle) or a larger 5.2 cleanup for 2020.

**Comment by jungshadow** [comment]
@jdmgoogle A few thoughts to your questions.

> How many states or counties have something like this in place?

Though I'm not sure of the overall number, quite a few states have some way for absentee and UOCAVA voters to track their ballots.

> How many people use such a feature?

Unsure of the numbers. I believe there are some studies that mention absentee voters feel more secure knowing that a method to track their ballot exists (even if they don't use it). @afsmythe, y'all have one. Do you have anything you can share?

> Where this data would get surfaced?

I'd surface it on all appropriate election admin elements. Since ballots go out for UOCAVA voters much earlier, it's useful info for a good number of people, even if polling locations and ballot data aren't available, yet.

> I support the idea and it makes sense for the spec. The question is if this should go into a 5.1.x release (maybe ready in time for this cycle) or a larger 5.2 cleanup for 2020.

Awesome. Personally, I'd love to see it in the spec sooner&ndash;mostly to prep election officials who might be willing to share the data&ndash;but I don't have any strong objections pushing it into 5.2.

Thanks!

**Comment by lbirdpew** [comment]
@jungshadow thanks for the answers, I'd add to them, but I think you covered them as completely, if not more than, I could.  I also checked and Pew doesn't have any research in this narrow field, but can ask around to the usual suspects for more info.

@jdmgoogle I think this would better served as a 5.1.x release for 2018.  There is a desire from jurisdictions for this ability and a compelling use case for it.

**Comment by MariaBianchi** [comment]
@jdmgoogle This is something that was mentioned as being valuable by states at a convening we ha with VIP partners at NASED this summer.

It's most visible in the vote by mail states, but @jungshadow is right, there's also somewhere in the majority of states and many counties that allows voters to look up at least the the received status of their absentee ballot.

We'd surface this data in the VIT with other election administration information in the short term, though in the long term we might also highlight it in states that have drop box objects present in their feed.

Like @lbirdpew, I think that if it's straightforward to add to the 5.1.x release, this could be used in 2018, and I'd love to start getting states to include it in their feed.

**Comment by jdmgoogle** [comment]
Brainstorming out the necessary work, we'd need to:

- update the spec to include this link;
- release a 5.1.2 version of the spec;
- update the Google pipeline to ingest this field specifically;
- update the Civic Info API to include this field; and
- update the VIT to show the API result.

@lbirdpew @MariaBianchi Does that seem to capture the scope of the work? Did I miss or overstate anything?

**Comment by MariaBianchi** [comment]
That captures most of it. We'll also want to update the documentation, and on the DW side will need to make a small adjustment to our processor to capture this new link.

**Comment by jdmgoogle** [comment]
Update from the EAC: there's also a requirement to allow tracking of provisional ballot status.

**Comment by afsmythe** [comment]
This has been resolved with PR https://github.com/votinginfoproject/vip-specification/pull/389 which is a part of the 5.2 revision.
