### ISSUE TITLE
Is ElectoralDistrict improperly labeled as "Optional" for ContestBase and Precinct

### ISSUE THREAD

**Issue by afsmythe** [votinginfoproject/vip-specification#368]
The `ElectoralDistrictId` field is labeled as "Optional" for the two objects below: 

[ContestBase](http://vip-specification.readthedocs.io/en/latest/built_rst/xml/elements/contest_base.html)
[Precinct](http://vip-specification.readthedocs.io/en/latest/built_rst/xml/elements/precinct.html)

Per the [XSD](https://github.com/votinginfoproject/vip-specification/blob/master/vip_spec.xsd), should this be labeled as "Required"? Just looking for another set of eyes for confirmation and I'll make the change in a new PR. It's caused some confusion for Louisiana including ballot data in their feed.

**Comment by jdmgoogle** [comment]
Per the current spec, the `ElectoralDistrictId` field is [required](https://github.com/votinginfoproject/vip-specification/blob/vip52/vip_spec.xsd#L275) for `ContestBase` but the `ElectoralDistrictIds` field is [optional](https://github.com/votinginfoproject/vip-specification/blob/vip52/vip_spec.xsd#L554) for `Precinct`.

**Comment by afsmythe** [comment]
Woops - please disregard my closing the issue. Sorry!

**Comment by afsmythe** [comment]
This has been corrected within [this PR](https://github.com/votinginfoproject/vip-specification/pull/369).
