### ISSUE TITLE
Support specifying the number of write-in places

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#37]
Currently, the `write_in` field is a simple yes or no.  It would be better if the field specified the number of write_in spaces (e.g. in "vote for N" races).

**Comment by pkoms** [comment]
It seems like we should also support describing whether write-ins can be arbitrary or have to have qualified. Tentatively, I'm starting to think that write-ins should be an optional object rather than a field.

**Comment by jdmgoogle** [comment]
Update the documentation to indicate that when this field is true, it means that one or more write-in candidates are allowed for this contest.
