### ISSUE TITLE
Support RCV voting style

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#38]
It would be good if the specification let one specify that ranked-choice voting (RCV) is being used in a contest.  Also, it would probably make sense to let one specify the number of candidates that the ballot lets one rank in this case (e.g. three in San Francisco).

**Comment by jdmgoogle** [comment]
I'll be putting forth a proposal to merge the ballot information portions of the IEEE P1622.2 election night reporting standard with VIP. The P1622.2 standard supports RCV.

**Comment by cjerdonek** [comment]
> I'll be putting forth a proposal to merge the ballot information portions of the IEEE P1622.2 election night reporting standard with VIP. The P1622.2 standard supports RCV.

@jdmgoogle Thanks. A few questions on the above:

1. Is there a newer version of the draft standard than what is posted on the VSSC 1662 web site [here](http://grouper.ieee.org/groups/1622/groups/2/index.html) (under "2014-11-24 Version for 1st round IEEE balloting"). That version doesn't seem to support RCV beyond including "IRV" in the "VoteVariation" enum.

2. Do you have an estimate on when you might put forth a proposal (e.g. on the order of one month from now, six months from now, or a year from now), and will you be waiting for 1622.2 to approve their document before doing so (it would be good to know if you have any idea on the time frame for that as well)?

3. Does VIP have a general philosophy of how its work should relate to the work of VSSC 1622?  For example, is VIP completely separate because it has a different purpose, or are there plans to switch to VSSC's standards once those are complete (and possibly influence the standards prior to adoption)?

**Comment by cjerdonek** [comment]
@jdmgoogle Can you respond to the questions I wrote above?  Obviously, you've already answered the first part of (2) :grinning:, but it's not clear to me if what you merged is the latest draft from VSSC or something that they have already adopted.

**Comment by jdmgoogle** [comment]
@cjerdonek 

1) The latest draft available to the public is the one on the website (from 2014/11/24). The latest rough draft isn't available to the public just yet, but I (and some of the people here) have been working to update it based on the public feedback. It should be available to the public for comments in something on the order of a few weeks, but I've been trying to keep the spec here as closely in alignment with the upcoming P1622.2 revision.

3) VIP and P1622 cover overlapping but slightly different areas. Both will contain ballot information, which we are attempting to harmonize here. VIP will cover the "where do I vote" portion of election information, whereas P1622.2 will not. P1622.2 will cover election results, whereas VIP will not.

**Comment by jdmgoogle** [comment]
I contacted Doug Jones at the University of Iowa about how to be parameterize and represent the differences in the different types of voting methods a voter would encounter. Here is his response:

===
IRV refers to a method of detrmining the winner from a collection of ranked-choice ballots.  Ranked-choice refers to a type of ballot where voters can rank their preferences. Ranked choice ballots can be counted by many different variants of IRV, STV (single transferrable vote, which is equivalent to some variants of IRV unless you are in a multi-seat district), Borda Count (simple sum of the rankings) and several others.

So, focus on ranked choice ballots, and clearly, the primary variants from the ballot point of view are:

Rank from A to B of between N and P out of M candidates.
- If A = 0 and B = 1, we get:
- - If N=1 and P=0, this is conventional plurality
- - If N=P, abstention is forbidden
- - If N=M and P=0, we support approval voting.

- If A = N = 1 and B = P = M it is: ranked-choice without abstention

In addition, you need flags indicating whether duplication in the rankings are permitted (as in approval voting) and you whether gaps in the rankings are permitted.  At one extreme (IRV) you must vote 1 2 3 4.  For approval voting, you vote 1 1 0 1, for other schemes, you might vote 1 2 2 4.

In sum, this seems to be an all inclusive set of attributes for a race:

A -- minimum ranking permitted per candidate
B -- maximum ranking permitted per candidate
N -- minimum number of candidates that must be ranked
P -- maximum number of candidates that must be ranked
M -- number of candidates
D -- boolean, if true, duplicate rankings are permitted (0 1 1 2)
G -- boolean, if true, gaps in the rankings are permitted (1 5 7)

This does assume that votes of 0 carry less weight than votes of 1 which carry less weight than votes of 2, etc.
---

The above is entirely a matter of ballot representaiton, not presentation.  It is useful to separate the presentation layer (specifying how the alternatives are presented) from the representation layer, just as it is useful to separate the representation layer from the counting layer.

Some IRV systems may say "rank your first choice candidate 1, your second choice 2, ..." while others may say "rank your first choice 5, your second choice 4 ..."  These are merely different presentation conventions.
===

I'd like to just toss this out to the crowd on next steps. Cc: @cjerdonek @pstenbjorn @jungshadow @jktomer

**Comment by cjerdonek** [comment]
At this point (with respect to pull request #43 and the discussion we had at the meeting), I think the most important things for the spec to capture are--

1. _what_ the voter is supposed to do from an instruction standpoint (e.g. rank up to N candidates, choose up to N candidates, etc), and
2. at the highest level, _how_ the ballots are counted (e.g. [instant runoff](http://en.wikipedia.org/wiki/Instant-runoff_voting), [first-past-the-post](http://en.wikipedia.org/wiki/First-past-the-post_voting), [equal and even cumulative](http://en.wikipedia.org/wiki/Cumulative_voting), etc).

I don't think we should try to get into documenting all of the variations and combinations of variations within each type of voting, and even more so if we can't point to any jurisdictions in the US that actually use it, and if it doesn't affect the instructions given to the voter.

I would be happy to put together a PR.  I expect it would differ only slightly from what has already been proposed for PR #43.

**Comment by jdmgoogle** [comment]
I'm following up with Doug Jones about which methods are commonly used in the U.S.

As for your points, regarding (1) I think Doug's framework flexibly describes everything we'd ever want and in a way that could be easy to program. Regarding (2), I think that's what the current VoteVariations enum tries to do, although that's more of a TallyVariations than VoteVariations.

Proposal: create a VoteVariations object which contains Doug's variables, and rename the current VoteVariations enum to TallyVariations (or some other name better than that, since that's a bit awkward).

**Comment by cjerdonek** [comment]
Hmm, I'm not sure abstracting things in the way that Doug suggests would really help things or is even the right way to go.  (I have several issues with the proposed abstraction.)  It also doesn't even address the [original issue](https://github.com/votinginfoproject/vip-specification/commit/cb6948e00dcfc3cead20adb97d23a602bd79ddb5#commitcomment-10157902) I raised with the enum, which was about cumulative voting and was really the only issue I had with the original enum.

One of the reasons I suggested not trying to be exhaustive here and sticking to 1622.2's simple enum is that it doesn't seem like there is time for such a discussion within the VIP 5 timeframe (there is a whole [VSSC working group](http://grouper.ieee.org/groups/1622/work-in-progress.html) devoted to this topic alone).  If people think otherwise, I can start listing my comments.

Also, just so people know, there are only about ten jurisdictions or so in the US that even use a ranked ballot (compared with [over fifty](http://en.wikipedia.org/wiki/Cumulative_voting#History) that use cumulative), so I think it's overkill to try to come up with some kind of general scheme.

**Comment by jdmgoogle** [comment]
Could you describe some of the issues you have with Doug's abstraction?

My understanding of the VSSC working group -- at least what Kenneth described in his presentation in LA last month -- is that they're attempting to come up with a *process* model (not just a data model) for the entire end-to-end election management experience. Unfortunately the website doesn't do a great job of explaining this, but I can ping them and see if they can clarify.

I tried to verify the claim in Wikipedia based on the supporting documents, but I couldn't find anything. There was an article about the Board of Regents for a college, but nothing supported the "fifty jurisdictions" claim. Did I miss one of the citations?

**Comment by cjerdonek** [comment]
Re: the working group, I was referring to a different working group, namely 1622.6, "Recommended Practice for Voting Methods Mathematical Models," which is described in part:

> "Voting methods are methods of casting, tabulating, mathematical evaluation, or counting votes, to determine the outcome of elections. Examples of voting methods include but are not limited to plurality voting, plurality with runoff, ranked choice, approval voting, straight-party voting, and multi-party endorsement. This standard satisfies the need for formal and precise mathematical reference models ..."

Re: Wikipedia, I was referring to these sentences in the section I linked to:

> "As of March 2012, more than fifty communities in the United States use cumulative voting, all resulting from cases brought under the National Voting Rights Act of 1965. Among them are Peoria, Illinois for half of its city council, Chilton County, Alabama for its county council and school board, and Amarillo, Texas, for its school board and College Board of Regents.[4] Courts sometimes mandate its use as a remedy in lawsuits brought under the Voting Rights Act in the United States; an example of this occurred in 2009 in Port Chester, New York,[5][6][7] which had its first cumulative voting elections for its Board of Trustees in 2010.[8]

I will respond on some of the issues later today.

**Comment by jdmgoogle** [comment]
Ah okay, I forgot about .6 and was thinking about .4. Which reminds me that I should bring Doug's comments to the attention of the .6 group.

And yes, in my previous comment I was referring to the citations in the block of text you quoted; none of them seem to mention fifty jurisdictions using cumulative voting, although I may have missed it. In which citation link does it mention the fifty jurisdictions using cumulative voting?

**Comment by cjerdonek** [comment]
For more specific support re: the fifty jurisdictions, here is a [FairVote page](http://archive.fairvote.org/?page=2101) with a list.

**Comment by jdmgoogle** [comment]
Generally speaking, providing links to your own (or own group's) research isn't kosher per Wikipedia, but I did a spot check of several of those jurisdictions and it seems to check out. :)

Getting back to the original point, in which way(s) do you feel that Doug's abstraction doesn't work?

**Comment by cjerdonek** [comment]
> Could you describe some of the issues you have with Doug's abstraction?

Here are some of my comments.  My apologies in advance for the long post, but this is why I warned in a previous comment that I didn't think we should be wading into this direction in the VIP 5 timeframe.  The water can get deep quickly, and the currents strong!

As I said in one of my previous comments, there are about ten jurisdictions in the country using IRV/STV.

Whether or not the below is exhaustive from a theoretical perspective, practically speaking, I believe the following three things would be more than enough for the spec to capture on the vote-casting side (at last week's meeting, we agreed to restrict to vote-casting and not cover tallying, where there are different types of variations):

1. number elected (already covered by `numberElected`; note that 1 means IRV),
2. max number of rankings (already covered by `votesAllowed`), and
3. number of write-in slots (I raised this as issue #37).

Beyond this, as far as I'm aware, in no jurisdictions are IRV/STV voters supposed to (a) skip rankings (e.g. choose a 1st and 3rd with no 2nd choice), (b) choose more than one candidate for the same ranking (e.g. rank two candidates 1st), or (c) rank the same candidate multiple times (e.g. mark the same candidate 1st, 2nd, and 3rd).  In other words, the instructions for what voters are supposed to do are the same in all cases.  For example in California, the four Bay area cities of San Francisco, Oakland, Berkeley, and San Leandro that use IRV all have the same rules on the vote-casting side.  I also know that Minneapolis, MN has essentially the same IRV instructions.  I would be surprised if any of the others differ in these respects.

So if we can already characterize IRV/STV vote-casting with what is currently in the spec (provided issue #37 is addressed), the bigger question in my mind is, "what problem is this scheme trying to solve?"  It seems more like an academic exercise or a solution in search of a problem.

As for the scheme itself, here are some specific issues:

1. The scheme is not DRY relative to the enum (i.e. there is redundancy).  Specifically, if we already have an enum value for "approval", what value is there in specifying it again as `A=0, B=1, N=M, P=0`?  And similarly for "N-of-M"?  People shouldn't have to store (or consume) the same information in multiple spots.  Because of this, it doesn't seem like the right abstraction.

2. The scheme is not exhaustive, even putting aside the tally aspect. For example, it doesn't seem like the scheme covers the points method of cumulative voting (though in fairness, I don't know off-hand if the points method of cumulative voting is actually used in any US jurisdictions).  As another example, the scheme covers "D, duplicate rankings" (assigning the same ranking to more than one candidate) and "G, gaps in the rankings," but it doesn't cover whether a candidate can be assigned multiple rankings.  In San Francisco, for example, voters _can_ rank the same candidate multiple times on a ballot (e.g. by marking the same candidate 1st, 2nd, 3rd).  Doug was quoted as saying, "In sum, this seems to be an all inclusive set of attributes for a race," but even this many-variable scheme doesn't seem to be so.

3. "A -- minimum ranking permitted per candidate": This seems theoretical. Are there any contests where voters are actually required to rank every candidate?

4. "N -- minimum number of candidates that must be ranked": Again, this seems theoretical. Are there any contests where voters are actually required to rank a certain number of candidates?

5. "P -- maximum number of candidates that must be ranked": Again, are there any contests with such a requirement?  I want to stress that we should stick to actual needs so as not to complicate the spec unnecessarily.

6. "D -- boolean, if true, duplicate rankings are permitted (0 1 1 2)": This boolean seems overly simplistic to me.  Let me explain.  In reference to the overall scheme, Doug was quoted as saying, "The above is entirely a matter of ballot representation," but there is actually a bit more going on here.  It's not clear what the boolean `D` should mean.  For example--

  * There is the matter of whether the ballot _physically_ permits voters
    to cast duplicate rankings (in San Francisco, for example, the answer
    is yes).
  * There is the matter of whether voters are "supposed" to cast duplicate
    rankings, even if the ballot physically allows it (in San Francisco,
    the answer is no).  In other words, it could be _physically_ permitted, but not permitted for the purposes of having that vote _count_.
  * There is the matter of, if a voter does cast a duplicate ranking, what happens specifically?  Is
    the vote still valid entirely, partially, or not at all? (In San Francisco, for example, 
    the vote is invalidated at that ranking onwards.)  Here we are starting
    to get more into tally rules, but as you can see, tally rules can
    have an impact on voter instructions (a particular vote can be
    "permitted" but not "advisable").  This raises the question of whether
    separating vote-casting from tallying is the right abstraction,
    and if it is even possible (especially if tally rules are reflected
    in the ballot instructions).
  * Lastly, there is also the matter of, if a voter does cast a duplicate
    ranking, how is the vote stored or represented (in San Francisco, for
    example, it is stored as "overvote").

7. "G -- boolean, if true, gaps in the rankings are permitted (1 5 7)": The same questions as (6) but for gaps.

8. The same questions as (6) but for assigning multiple rankings to the same candidate.

9. The same questions as (6), but for (3), (4), and (5).
  
If all of the above seems complicated (and even if it doesn't), I want to go back to my original point at the beginning of this comment and stress that a scheme like this doesn't seem necessary to me in the first place.

Trying to encapsulate a set of voting variations with integers and boolean flags (many combinations of which wouldn't correspond to rules in any actual US elections) doesn't seem to me to advance things in a practical way, and it seems like it may raise more questions than it answers.  And if there really is a need like this, a working group dedicated to this task seems more appropriate and better equipped (like 1622.6, where there is more time for discussion).

**Comment by jdmgoogle** [comment]
Thanks for the feedback. Comments inline.

> As I said in one of my previous comments, there are about ten jurisdictions in
the country using IRV/STV.

By this you mean "there are ten jurisdictions *currently* using one particular variant of RCV/IRV"?

The rest of your comments seem to assume that the only changes needed to this spec are those to support the particular variation of RCV/IRV used by San Francisco. If that's the explicit goal -- as opposed to a more broad definition which would support cumulative voting, Borda counting, approval voting, or other variants of RCV not used by SF -- then we should state that up-front.

> number elected (already covered by numberElected; note that 1 means IRV)

Does this mean that STV would be a separate enum since it is the variant of RCV for multi-seat elections?

> Beyond this, as far as I'm aware, in no jurisdictions are IRV/STV voters supposed to (a) skip rankings (e.g. choose a 1st and 3rd with no 2nd choice), (b) choose more than one candidate for the same ranking (e.g. rank two candidates 1st),

Both of these are to support approval voting and Borda elections, both used in various primaries and international elections.

> or (c) rank the same candidate multiple times (e.g. mark the same candidate 1st, 2nd, and 3rd). In other words, the instructions for what voters are supposed to do are the same in all cases.

The points method is supported using this approach; i.e., if you can cast up to N votes where each vote is of at most 1 point, but duplication is allowed, this is the points method.

> The scheme is not DRY relative to the enum (i.e. there is redundancy).

The proposal would be to do away with the enums and define a VoteVariation object, and each election would refer to the vote variation by voteVariationID instead of the enum.

> Are there any contests where voters are actually required to rank every candidate?

Off the top of my head I know that Australia requires every candidate to be ranked. I'm not sure of other places either internationally or in the U.S. which have this requirement.

> Are there any contests where voters are actually required to rank a certain number of candidates?

Think of this as not just "ranking" but "selections made." For example, Nevada has a "none of the above" option, meaning that the vote should -- technically -- make a selection in each contest, even if it's just "none of the above."

> "P -- maximum number of candidates that must be ranked": Again, are there any contests with such a requirement?

This would be the 'N' in the "N-of-M" specification.

>  In other words, it could be physically permitted, but not permitted for the purposes of having that vote count.

This appears to be a distinction without a difference. The vote is not permitted to make duplicate marks, even if a quirk of the UI (in this case, the paper ballot) allows those duplicate marks to be made. In either case the votes for that contest are discarded.

> Here we are starting to get more into tally rules, but as you can see, tally rules can have an impact on voter instructions (a particular vote can be "permitted" but not "advisable").

The ballot marking rules describe what is a valid ballot, whereas the tally rules describe how to aggregate the valid ballots. Any marks or selections which invalidate the ballot mean they are discarded prior to any tallying occurring. I don't see how this wanders into the "tally" phase.

> I want to go back to my original point at the beginning of this comment and stress that a scheme like this doesn't seem necessary to me in the first place.

Currently the ballot casting rules are represented by:

- enum value "approval"
- enum value "cumulative"
- enum value "IRV"
- enum value "N-of-M"
- (proposed by you) enum value "cumulative-points"
- votes_allowed

That's a total of six possible chunks of information, and it doesn't fully capture the range of ballot marking options. Removing the enums and replacing them with a VoteVariation object containing the five integers and two booleans provides significantly more flexibility.

I'd be more than happy to put you in touch with Doug if you have questions about how each of the various ballot marking schemes you've discussed (e.g., equal and even, points method, STV, etc) can be represented within his framework.

You are right, though, in the main question is "what are we trying to accomplish?" If the goal is just "support RCV in the SF Bay Area" then glomming on a flag here or there will do. I'll let the rest of the group weigh in here.

**Comment by jungshadow** [comment]
@cjerdonek @jdmgoogle If we can get a dataset from San Francisco for a previous election, we can absolutely adapt the schema if the current one doesn't work. For now, can we agree to work with the models we have and push these issues "upstream," so to speak (i.e. to VSSC)? I'm concerned that we're spending a lot of time on this one issue and it may be something that should be addressed with the folks at the VSSC. Sound fair?

**Comment by jdmgoogle** [comment]
Closed given the latest features in the 1622.2 schema.
