### ISSUE TITLE
Support multiple electoral districts for an office?

### ISSUE THREAD

**Issue by rsimoes** [votinginfoproject/vip-specification#396]
In the past couple years we've been researching further down ballots across the United States, and in the course of that we've been discovering a growing number of offices with jurisdictions and electoral districts consisting of unnamed, contiguous sets of smaller regions. As just one example, the Sheriff of Fairfax County, Virginia is elected by and has jurisdiction over Fairfax County, Fairfax city, and the towns of Herndon and Vienna.

With these districts in consideration, would there be any inclination among the core VIP spec maintainers to add support for multiple electoral districts for an office? An alternative solution would be to start minting aggregate OCDIDs for these districts, but we would rather not pollute the ID repository with dozens of such additions.

**Comment by afsmythe** [comment]
Thanks for raising @rsimoes! My first inclination is that creating new OCDIDs for such districts wouldn't be a "pollution" of the repo, because it is a singular jurisdiction for the Office. Could you give an example of why such new OCDID's would be messy?

Also, we'll want data consumers (Google) to weigh in on this. VIP is still working with states to incorporate OCDIDs, and so unfortunately we don't have any real-world examples of how a data provider would encode such a jurisdiction, and even if they'd prefer the option to provide multiple jurisdictions for an Office element.

**Comment by jdmgoogle** [comment]
As someone familiar with the northern Virginia area, I can let you know that Herndon and Vienna are both unincorporated areas within the boundaries of Fairfax County. I'm not sure if there are areas within Fairfax County that are _not_ served by the Sheriff.

That said, Fairfax City is its own incorporated area.

We've also seen instances where there are _contests_ which span multiple districts; e.g., two adjacent school districts which are voting whether or not to merge. This geographic region (a)exists solely for the purpose of the election, (b) would not be relevant after the election if the vote fails, and (c) would be difficult to name.

I agree that the cleaner long-term solution would be to allow offices and contests to specify multiple districts, although that'll probably create some medium-term challenges around the pipeline and NIST compatibility.

@jloutsenhizer FYI

**Comment by whittsxnbq** [comment]
Having combined districts like this is pretty common.  The way this is sometimes modeled in the VRDB is that you create a separate district for the combined district.  For example in WI we have combined court districts that consist of multiple counties.  So we created a separate Court district to represent the geographic area of the combined counties (example:  Menomonee Shawano).  We have a similar thing with multi-jurisdictional municipal judges who cover several villages and townships.  So we create a single combined district that covers all of the component districts.  This allows us to maintain the one to one relationship between a contest and a district.  It also allows the office holder to represent a single district.  And it simplifies the creation of precinct-splits.  We also assign a separate OCD ID for the combined district.  If you want to know the component parts of a combined district, it is frequently included in the district name.  It is also impled in our VIP feed via the relationships between precinct-splits and electoral districts.  It is also implied in our NIST Election Results Reporting files (1500-100) through the same relationships.

**Comment by afsmythe** [comment]
I may be wrong, but it seems like there is a possibility of slippery slope here, where the spec could allow for an executive type of `Office`, say Governor, to list all of the `ElectoralDistrictIds` within the State, rather than a single `ElectoralDistrictId` for the State. Would that scenario be ideal for data consumers, or would we somehow limit the number of `ElectoralDistrictIds` assigned to an `Office`?

**Comment by rsimoes** [comment]
> I may be wrong, but it seems like there is a possibility of slippery slope here, where the spec could allow for an executive type of `Office`, say Governor, to list all of the `ElectoralDistrictIds` within the State, rather than a single `ElectoralDistrictId` for the State. Would that scenario be ideal for data consumers, or would we somehow limit the number of `ElectoralDistrictIds` assigned to an `Office`?

This would be up to the data provider. It would certainly be wise to ensure an office or contest references the minimum number of districts unless there is a application-specific reason to reference more.

**Comment by jdmgoogle** [comment]
Good point @afsmythe. And while it might be up to the data provider, @rsimoes, I think they'd have to understand that if (for example) they said that the electoral district of the Governor of Texas was [list of all 240ish Texas counties] that a lot of data consumers wouldn't know what to do with that.

Maybe something like `SecondaryElectoralDistrictIds`? Or would this be something to enforce more by convention and social norms?

**Comment by afsmythe** [comment]
I think we should punt on this to allow for more input. Any objections? And is there a strong reason to include this in the 5.2 revision for theoretical use in 2020?

**Comment by rsimoes** [comment]
@afsmythe We'll survive without it

**Comment by jdmgoogle** [comment]
+1 on punting

**Comment by whittsxnbq** [comment]
I also agree with punting.  If this hasn't come up so far from the folks providing the VIP data, I think we are OK.  Maybe we can take this up if a data provider has this situation and doesn't know how to handle it in the feed.

**Comment by afsmythe** [comment]
Propose we close this.
