### ISSUE TITLE
CSV spec should support InternationalizedText

### ISSUE THREAD

**Issue by afsmythe** [votinginfoproject/vip-specification#399]
Serving as a placeholder for inclusion of `InternationalizedText` within the CSV implementation. This shouldn't require any updates to the core 5.x XSD and we will make comments to this Issue as progress is being made.

**Comment by jdmgoogle** [comment]
Is this a 5.2 blocker, or post-5.2 release?

Attn @jswiesner

**Comment by afsmythe** [comment]
Not a blocker for 5.2. Assigning to 5.3 but there is no timeline for this CSV work in place at this moment.

**Comment by jswiesner** [comment]
Since we are actively looking at 6.0 as the next version of the spec, it's unlikely we will have a version 5.3. That said, and considering there is no plan for CSV work at the moment, can we create a 6.1 milestone and assign this issue to it? 6.1 would become the placeholder for the "next next" verison.

**Comment by afsmythe** [comment]
This item isn't actually related to spec development (the XSD) and the current landscape around `InternationalizedText` is laid out below:
- v5 XML data providers can provide `InternationalizedText` (translations) in their feeds if they choose to. Currently no states are doing so
- v5 CSV data providers do not have the ability to provide translations in these flat files. There is some complexity around flattening multiple translations within the current [CSV data format](https://vip-specification.readthedocs.io/en/release/csv.html), and so this transformation is not currently supported. 

If there were to come a time where CSV files were a published format of VIP data (in addition to XML) then this issue would be more significant. But if states want translations in their feeds, they really should be providing XML. 

I'm happy closing this issue instead of punting to future milestones.

**Comment by jswiesner** [comment]
+1 to that sentiment - states should be motivated to move away from CSV in order to take advantage of the more robust features offered by XML. Agree with closing.
