### ISSUE TITLE
Distinguish Vote Centers from Early Voting Sites

### ISSUE THREAD

**Issue by Jared-Prime** [votinginfoproject/vip-specification#409]
Some states, as an alternative to precinct-based polling locations, offer a "vote center" to their constituents. The voter center is open to all voting eligible residence within the election jurisdiction; this election model expands the number of potential locations available to vote on election day. See [NCSL Vote Centers](https://www.ncsl.org/research/elections-and-campaigns/vote-centers.aspx) for a brief policy overview and a list of state laws governing the establishment and usage of vote centers.

Currently, the VIP spec passively supports the presence of vote centers -- by manual inspection of the data returned by the Civic Info API, these are contained within the `pollingLocations` enumeration. I'm uncertain, but I'm guessing that any vote center that also qualifies for inclusion in the `earlyVoteSites` or `dropoffLocations` enumerations could be found there.

However, note that the VIP spec only gives a [`PollingLocation`](https://vip-specification.readthedocs.io/en/release/built_rst/xml/elements/polling_location.html) object, within which there's two optional boolean flags `IsDropBox` and `IsEarlyVoting`, that distinguish these separate enumerations.

As a consumer of VIP election data and of the Civic Information API, it would be helpful to distinguish vote centers through metadata and through enumeration (respectively). Presently, it's _possible_ to infer that a given item in `pollingLocations` is, in reality, a vote center by NCSL definition, but it's not immediately clear that such an inference is correct and consistent with the election policy.

**Comment by Jared-Prime** [comment]
Sorting out my confusion here might just involve a bit of documentation -- but I could also see a clear benefit to adding the metadata and/or API response object, so that consumers can process vote centers in a straight-forward, programmatic way.

**Comment by jungshadow** [comment]
Hi @Jared-Prime! This is already supported in the structure of the data standard. Whether a `PollingLocation` adheres to a particular state's policy on vote centers will depend on the `PollingLocation`—and its features—and the geopolitical unit with which it's associated. `PollingLocation` elements can be associated with `Precinct`, `Locality`, and `State` elements. One county may introduce a vote center model, but another county may still follow a traditional precinct-to-polling-location relationship. See the example below of a polling location that's available to all voters within Albermarle County and opens a few days before the November 5, 2013 election (NB: I'm skipping all of the additional elements needed to make this a valid feed):

```xml
<Locality id="loc70001">
  <ElectionAdministrationId>ea40001</ElectionAdministrationId>
  <ExternalIdentifiers>
    <ExternalIdentifier>
      <Type>ocd-id</Type>
      <Value>ocd-division/country:us/state:va/county:albemarle</Value>
    </ExternalIdentifier>
  </ExternalIdentifiers>
  <Name>ALBEMARLE COUNTY</Name>
  <PollingLocationIds>pl81274</PollingLocationIds>
  <StateId>st51</StateId>
  <Type>county</Type>
</Locality>

<PollingLocation id="pl81274">
   <AddressLine>ALBEMARLE HIGH SCHOOL</AddressLine>
   <AddressLine>2775 Hydraulic Rd</AddressLine>
   <AddressLine>Charlottesville, VA 229018917</AddressLine>
   <HoursOpenId>hours0001</HoursOpenId>
   <IsEarlyVoting>true</IsEarlyVoting>
   <LatLng>
     <Latitude>38.0754627</Latitude>
     <Longitude>-78.5014875</Longitude>
     <Source>Google Maps</Source>
   </LatLng>
</PollingLocation>

<HoursOpen id="hours0001">
  <Schedule>
    <Hours>
      <StartTime>06:00:00-05:00</StartTime>
      <EndTime>12:00:00-05:00</EndTime>
    </Hours>
    <Hours>
      <StartTime>13:00:00-05:00</StartTime>
      <EndTime>19:00:00-05:00</EndTime>
    </Hours>
    <StartDate>2013-11-02</StartDate>
    <EndDate>2013-11-05</EndDate>
  </Schedule>
</HoursOpen>
```

The standard can support a vote center model, but I'm curious about your use case. Are you looking to impart some specific piece of information about vote centers to voters?

**Comment by afsmythe** [comment]
Is the value to users in identifying `PollingLocation` records as a "Vote Center" (as defined by NCSL) or is the value in letting users know that the jurisdiction in which they live (either `State`, `Locality` or `Precinct`) is a "Vote Center" jurisdiction? Or, both?

Also, I'm a little confused by the title of this Issue. Election Day sites (either a NCSL defined Vote Center or not) and Early Voting Sites are already distinguished via the `PollingLocation.IsEarlyVoting` boolean flag. If a particular voting location is a "Vote Center" and is available for both early voting and election day then I believe the location would need to be provided as two records in VIP feeds with each record toggled on the `PollingLocation.IsEarlyVoting` boolean flag.

**Comment by afsmythe** [comment]
Closing this.
