### ISSUE TITLE
Add Office object

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#42]
Currently, the Contest object references the office via an "office" string field.  This issue is to suggest adding an Office object, in which case the contest field would become an office ID.

The advantage of doing this is mostly around DRY.  For example, if we add translations of the office name per issue #39 (which could potentially be many), it would be annoying to have to repeat these same translations in every Contest (e.g. for every district).  We may also find that offices have other useful attributes (e.g. the URL to the office's web site, physical address of the office, term of the office, description, etc).

Another advantage of breaking this out is that it's likely that the Office objects will remain the same from election to election, so Departments of Election could prepare this data separately (potentially by hand), independent of any particular election, and then reuse the same data.

**Comment by djbridges** [comment]
I think this is a good idea, both on the merits Chris mentions and
(selfishly) because it will make it much easier for ballot information to
play nice with elected official/other civic engagement datasets.

On Tue, Mar 10, 2015 at 12:41 PM, Chris Jerdonek <notifications@github.com>
wrote:

> Currently, the Contest object references the office via an "office" string
> field. This issue is to suggest adding an Office object, in which case the
> contest field would become an office ID.
>
> The advantage of doing this is mostly around DRY. For example, if we add
> translations of the office name per issue #39
> <https://github.com/votinginfoproject/vip-specification/issues/39> (which
> could potentially be many), it would be annoying to have to repeat these
> same translations in every Contest (e.g. for every district). We may also
> find that offices have other useful attributes (e.g. the URL to the
> office's web site).
>
> Another advantage of breaking this out is that it's likely that the Office
> objects will remain the same from election to election, so Departments of
> Election could prepare this data separately (potentially by hand),
> independent of any particular election, and then reuse the same data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/votinginfoproject/vip-specification/issues/42>.
>



-- 
Donny Bridges | Director of Civic Data | The Center for Technology & Civic
Life | 202.549.3717 | donny@techandciviclife.org

**Comment by jdmgoogle** [comment]
Please see #43.

**Comment by cjerdonek** [comment]
I've changed my thinking on this issue a bit since last week and after having a chance to think more and play around with examples.

Rather than trying to model "persistent" objects in VIP at this point like offices and bodies (independent of an election), I think it would be sufficient simply to add an "external_identifiers" collection to the Office type proposed in the 1622.2 PR #43.  This would let offices / bodies / etc be modeled outside of VIP, while still allowing VIP to link to that data (and thus still satisfying @djbridges's stated desire to "make it much easier for ballot information to play nice with elected official/other civic engagement datasets").

**Comment by djbridges** [comment]
No objection here - as long as there's a hook in there, I'm happy.

On Tue, Mar 17, 2015 at 3:23 PM, Chris Jerdonek <notifications@github.com>
wrote:

> I've changed my thinking on this issue a bit since last week and after
> having a chance to think more and play around with examples.
>
> Rather than trying to model "persistent" objects in VIP at this point like
> offices and bodies (independent of an election), I think it would be
> sufficient simply to add an "external_identifiers" collection to the Office
> type proposed in the 1622.2 PR #43
> <https://github.com/votinginfoproject/vip-specification/pull/43>. This
> would let offices / bodies / etc be modeled outside of VIP, while still
> allowing VIP to link to that data (and thus still satisfying @djbridges
> <https://github.com/djbridges>'s stated desire to "make it much easier
> for ballot information to play nice with elected official/other civic
> engagement datasets").
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/votinginfoproject/vip-specification/issues/42#issuecomment-82582097>
> .
>



-- 
Donny Bridges | Director of Civic Data | The Center for Technology & Civic
Life | 202.549.3717 | donny@techandciviclife.org

**Comment by cjerdonek** [comment]
Closing this as the 1622.2 related PR #43 added an Office object with external identifiers.
