### ISSUE TITLE
Release VIP 6.0

### ISSUE THREAD

**Issue by jswiesner** [votinginfoproject/vip-specification#425]
This issue is for tracking the release of version 6.0. We'll need to create a new release in this repo from the `vip6` branch when ready.

Completed steps preparing for release:
- All 6.0 XSD changes applied to [vip_spec.xsd](https://github.com/votinginfoproject/vip-specification/blob/vip6/vip_spec.xsd)
- [Readthedocs](https://vip-specification.readthedocs.io/en/vip6/) updates to include all changes for 6.0
- Updated [HISTORY.md](https://github.com/votinginfoproject/vip-specification/commit/b00b815606adb4966bd9a5aedadac3ed7096d67f) to include 6.0 changes

Remaining steps for release:
- Create tag "v6.0-release" targeting branch `vip6`
- Create new [release](https://github.com/votinginfoproject/vip-specification/releases)

**Comment by jswiesner** [comment]
@afsmythe is there anything else that I missed that needs to be completed for the 6.0 release? And do you feel we are ready to proceed with the 6.0 release? If so, I'm happy to create a draft release for review.

**Comment by afsmythe** [comment]
Thanks for raising this! It doesn't look we've created a "release" for the 5.2 revision yet. Would you mind tacking that on to the 6.0 release work?

**Comment by jswiesner** [comment]
That sounds good. I also thought of two other remaining steps prior to release. The updated list looks like the following. Let me know if you think of anything else.

- Create release for version 5.0
- Add a sample feed for 6.0 (#426)
- Add comments to documentation Python script (#279 )
- Create tag "v6.0-release" targeting branch `vip6`
- Create new [release](https://github.com/votinginfoproject/vip-specification/releases) for 6.0

**Comment by jswiesner** [comment]
@afsmythe I'm working on the 5.2 release now. We could cut this release from the `vip52` branch, but there's a few useful commits in master since the latest commit in vip52 that IMO would be worth including with the release. Which branch do you think we should issue this release from?

**Comment by afsmythe** [comment]
I think we'll want to cut from the [`release`](https://github.com/votinginfoproject/vip-specification/commits/release/) branch. Does that sound correct?

**Comment by jswiesner** [comment]
That makes sense to me, I didn't realize there was a release branch. Looking back at recent releases, we haven't used the release branch (or used the same strategy consistently for that matter). Do you know if the release branch was in use during these releases? Or has this branch only been used more recently than that?

- [5.1.2 release](https://github.com/votinginfoproject/vip-specification/releases/tag/v5.1.2-release) references ebc9b9cd3ed70db92fb45f8b52de73be0aa7d1de from the `master` branch
- [5.1.1 release](https://github.com/votinginfoproject/vip-specification/releases/tag/v5.1.1-release) references 8b3304d561dfc606b5d732ce7acc30e48351f79a from the `vip5111` branch
- [5.1 release](https://github.com/votinginfoproject/vip-specification/releases/tag/v5.1-release) references 50e304df5c8f314d87a9b5169f853bb247be5543 from the `vip51` branch

**Comment by afsmythe** [comment]
I don't think we've been consistent with branching, but this is a good time to agree on (and document) a best practice going forward :) The current documentation branching scheme was in place during the Pew days. 

[ReadTheDocs](https://vip-specification.readthedocs.io/en/release/) surfaces three different sets of documentation [`latest`, `vip6`, `release`]. The `latest` set points to the _master_ branch in Git. We've generally shared the `release` set with partners, and I believe this branch is current with regards to changes of VIP 5.2. The `vip6` set was recently activated to share with the feedback group. Prior to the vip6 work, only `latest` and `release` were surfaced in RTD. 

My assumption with this structure was that spec change proposals would go first to the _master_ Git branch (and surfaced by the `latest` RTD documentation set). I suppose _master_ would then merge in to _release_ once the proposal was published, but I don't think this has been followed consistently. 

This [guide](https://github.com/votinginfoproject/vip-specification/blob/release/CONTRIBUTING.md#pull-requests) does not provide much direction about which branches to cut and merge from. I can make a proposal after giving some of this some thought.

**Comment by jswiesner** [comment]
I like the idea of standardizing and documenting a branching strategy. My proposal would be to adopt a commonly used and well-documented git branching strategy. Two examples are [git flow](https://nvie.com/posts/a-successful-git-branching-model/) or [trunk-based branching](https://trunkbaseddevelopment.com/). The [Trunk Based Development](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development) article by Atlassian also includes a good comparison of the two. Using a common strategy will be easier for developers new to this repo to understand how the repo handles branching, and means we don't need to worry about maintaining and explaining our own strategy/documentation. 

Since this repo is not likely to be integrated with CI, and changes and releases are not frequent, something like git flow makes sense to me. WDYT about creating a new issue to discuss options for branching strategy so we can get more input from the community? 

In the mean time, I suggest we move forward with the 5.2 release from the current `release` branch, since I agree that branch is presently an accurate representation of 5.2. If we don't have consensus yet about the standardizing branching strategy by the time we are ready to publish the 6.0 release, we could follow the same approach for that release as well.

**Comment by jswiesner** [comment]
The 5.2 release is in draft stage (to be cut from the **master** branch - more on this below) and should be ready to go. If this looks good to you I'll go ahead and publish it: https://github.com/votinginfoproject/vip-specification/releases/edit/untagged-67c088d12182f90fda80

I noticed that the [schema version on L8 in the release branch](https://github.com/votinginfoproject/vip-specification/blob/ad45714deebcbadd207bf19098e4434a9e526f54/vip_spec.xsd#L8) is still out of date, so there's still at least one commit out of sync between master and release. Therefore I think master is the best branch to cut the 5.2 release from at the moment.

**Comment by afsmythe** [comment]
Thanks for putting the release in draft stage. Things LGTM. We might cherry pick commit 679c08c6d19244c61d31bfce998fc565a4bf08e0 in to `release` but can do that once the 5.2 release is _released_. I think `master` branch looks good to cut 5.2 from.

**Comment by jswiesner** [comment]
[Version 5.2](https://github.com/votinginfoproject/vip-specification/releases/tag/v5.2-release) is now released! As a side note for future reference, you don't need to manually upload any assets for source code when publishing a release. I had added these to the draft since I saw them in other releases, but after releasing I realized that they are also added automatically by GitHub. 

Also merging the cherry-pick of 679c08c6d19244c61d31bfce998fc565a4bf08e0 with #429.

**Comment by jswiesner** [comment]
With #445 merged, we should be able to close #279. Are we now ready to release 6.0? If so, I can create the release in draft stage for review.

**Comment by afsmythe** [comment]
Yes, I believe we're ready to release 6.0. Thanks for putting this together!

**Comment by jswiesner** [comment]
Great!

I just created a [draft for the 6.0 release](https://github.com/votinginfoproject/vip-specification/releases/edit/untagged-fe1a2f77b9e8ddb4766c). Could you take a look and let me know if it looks good? 

Once we push the release, we should also merge vip6 into master, and then master into release.

**Comment by afsmythe** [comment]
Looks good!

**Comment by jswiesner** [comment]
6.0 is now released!

I created #449 to merge vip6 into master, which has conflicts with the following files. As opposed to resolving individual conflicts I'm thinking we favor the vip6 version for all 4 of these files. Thoughts?

docs/built_rst/csv/single_page.rst
docs/built_rst/xml/single_page.rst
sample_feed.xml
scripts/vippy/rest.py

**Comment by afsmythe** [comment]
🎉 

Favoring the vip6 branch sounds safe enough.

**Comment by jswiesner** [comment]
There's a couple more cleanup tasks we need to do:

- We should change the default branch, it's currently set to `vip52`. I propose we change this to `master`. I don't think we should make `vip6` the new default since we don't expect any new changes to be made in that branch going forward. Also, I don't seem to have access to the repo settings, are you able to change this?
- We should update the readthedocs config now that v6 is published. I propose we keep two versions: latest (based on the master branch) and release (based on the release branch). Thoughts?
- For posterity I want to back port b9804a299ff800e8dea6fb8314e4033f4bebd2c9 to the `vip6` branch. But in preparing to do that, I noticed that the master branch (after vip6 got merged in) isn't fully in sync with the state of the `vip6` branch (for example, [this line](https://github.com/votinginfoproject/vip-specification/blob/b9804a299ff800e8dea6fb8314e4033f4bebd2c9/scripts/vippy/rest.py#L319) shouldn't be there. Are you able to tell which commits (if any) are missing from master?

**Comment by afsmythe** [comment]
I had a look at the [commit history](https://github.com/votinginfoproject/vip-specification/commits/master) and it looks like that line (`if mode == "xml":`) was merged in to `vip6` from `master` by commit 0d23987b5951ff306cd902d91b3c5b2ff213f2fe _after_ this commit b8179d37d99a1bab4a8afb76fce568998db6e642 (which removed the `if mode == "xml":` from `vip6`. That line was reintroduced to `vip6` after being removed. 

Can you have a look and confirm if I'm seeing this correctly?

**Comment by jswiesner** [comment]
Ah you're right. It was the merge from master -> vip6  (0d23987b5951ff306cd902d91b3c5b2ff213f2fe) preceding the merge from vip6 -> master that caused this. Looking at 0d23987b5951ff306cd902d91b3c5b2ff213f2fe, all the changes that were incorporated look right to me except the reintroduction of `if mode == "xml"`. Do you agree? If so, I can put together a PR to just remove those 3 lines from master.

**Comment by afsmythe** [comment]
Yes, I think that's correct, thanks!

**Comment by jswiesner** [comment]
That issue was fixed with #451. I also completed the back-port of the README update to `vip6` with #452. @afsmythe are you able to take the remaining two clean up tasks from my earlier comment?

> * We should change the default branch, it's currently set to vip52. I propose we change this to master. I don't think we should make vip6 the new default since we don't expect any new changes to be made in that branch going forward. Also, I don't seem to have access to the repo settings, are you able to change this?
> * We should update the readthedocs config now that v6 is published. I propose we keep two versions: latest (based on the master branch) and release (based on the release branch). Thoughts?

**Comment by afsmythe** [comment]
Yes. Will begin looking in to those items.

**Comment by afsmythe** [comment]
To confirm, after these suggestions we'll have both `master` and `release` branches to serve 6.0 revision?

**Comment by jswiesner** [comment]
Yes, at least for the time being. In the future we could merge other changes into master that weren't necessarily part of the release branch, since the release branch represents the latest officially published release version. I'm also not opposed to eliminating the release branch altogether and treating the master branch in the same way - it represents the most recent officially released version of the VIP spec.

**Comment by afsmythe** [comment]
Ok, that makes sense. But I think the `release` branch will need some attention since it is out of sync with `master` (which I've made the default). I will take a look at that. 

Readthedocs is updated so that `latest` points to the default branch in Git. We now only have two RTD branches, `latest` and `release`.

**Comment by jswiesner** [comment]
Awesome, everything looks great. I think there's still a broader discussion to be had around the optimal branching strategy for this repo, which we can discuss going forward.

Closing this issue out now that 6.0 is officially out the door!
