### ISSUE TITLE
Add sample feed for 6.0

### ISSUE THREAD

**Issue by jswiesner** [votinginfoproject/vip-specification#426]
We need to add a new sample feed to the repository for version 6.0. We could simply update the existing 5.2 sample feed, or we could add a new separate one. I would lean towards the latter since the [existing sample feed](https://github.com/votinginfoproject/vip-specification/blob/vip52/sample_feed.xml) is StreetSegment-based, and the 6.0 feed will be shape-based.

**Comment by jswiesner** [comment]
@afsmythe - does the VIP team have a 6.0 sample feed that can be shared for this purpose?

**Comment by afsmythe** [comment]
We do! Could the XML be uploaded on its own? Or should it be uploaded along with the shapefile dataset?

**Comment by afsmythe** [comment]
Please see this PR containing the updated `sample_feed` https://github.com/votinginfoproject/vip-specification/pull/427

**Comment by jswiesner** [comment]
I think we can close this now that #427 is merged. @afsmythe can you confirm?

**Comment by jswiesner** [comment]
I think we can close this now that #427 is merged, but just wanted to confirm one more time?

**Comment by afsmythe** [comment]
Yes, sounds good!

**Comment by jswiesner** [comment]
Sounds good. Closing this issue as a result of #427.
