### ISSUE TITLE
Use xs:ID and xs:IDREF for identifiers

### ISSUE THREAD

**Issue by jdmgoogle** [votinginfoproject/vip-specification#44]
We should move away from using xsd:integer and/or xsd:string types as identifiers, and move towards a more strongly typed model using xsd:ID and xsd:IDREF in as many places as is reasonable. This will allow for more rigorous checking of data and types, and allow everyone along the processing chain to verify that references are (at least) to items of the correct type.

Comments? Feedback?

**Comment by pstenbjorn** [comment]
@jdmgoogle the use of `xs:ID` (or `xsd:ID`) in place of `xs:string` or `xs:integer` for unique identifiers is certainly better practice to ensure global uniqueness.  My comment is that an `xs:ID` is based on the type `xs:NCName` - that means it must begin with an _ or a letter.  Most of the existing systems that generate VIP data generate IDs as integers.  However, to generate the 1622.2 schema I simply prepended an _ on the ids used.

**Comment by jdmgoogle** [comment]
Your thoughts, @jktomer?

**Comment by jktomer** [comment]
Bleh, I should have guessed that an `xs:ID` is like a C identifier; I was assuming without attention to the XSD spec that it was free-form. That's pretty annoying and will make life difficult for some data exporters.

On the other hand, I think Hungarian-style IDs ("ss12345" for street segments, "pp12345" for precincts) would probably be helpful in the long run (considering that more than once I've resorted to grepping VIP xml files to find a problematic record).

I'd be OK with falling back to `xs:string` if `xs:ID` feels like too much of a pain -- I really would like to move away from `xs:integer` though.

**Comment by jungshadow** [comment]
:+1: for the Hungarian-style IDs. Off the top of my head, I don't think we have any element abbreviation conflicts, but I'll create a new discussion issue that calls for them and one of the exercises will be creating an exhaustive list.

@jktomer I don't think anyone wants to go back to xs:integer :)
