### ISSUE TITLE
Create a "best practices" guide for creating a VIP feed.

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#45]
This is something that @jktomer [brought up](https://github.com/votinginfoproject/vip-specification/issues/44#issuecomment-78379427) in #44. If we move to `xs:ID` and `xs:IDREF`, this could be helpful in having more visually-useful prefixes other than an underscore or a random letter.

**Comment by jdmgoogle** [comment]
This seems to be a "best practices" for creating a VIP feed rather than having to do with the names of the XML objects, elements, or attributes. If that's the case we should have a bug for "create a 'best practices' guide."

**Comment by jungshadow** [comment]
@jdmgoogle Absolutely. Just wanted to have a placeholder to remind me.

**Comment by jdmgoogle** [comment]
Note that @pstenbjorn started this with #225.

**Comment by jdmgoogle** [comment]
@pstenbjorn In your opinion, what is left to do on this issue?

**Comment by pstenbjorn** [comment]
@jdmgoogle I think this should be closed.

**Comment by jdmgoogle** [comment]
@jungshadow @jen-tolentino @cjerdonek, do you have any additional comments?

**Comment by jungshadow** [comment]
Let's close. We can open other issues when we need to add something new/specific or if we need to fix/remove something.
