### ISSUE TITLE
Allow for named timezones

### ISSUE THREAD

**Issue by jennifertlovell** [votinginfoproject/vip-specification#458]
VIP spec requires UTC offset for structured hours in TimeWithZone element. Update in #457 relaxes regex, allowing for named timezones to be used instead of UTC offset. Proposed change, as currently written, is very permissive. Named timezone validation (validating that the value matches with an existing IANA timezone) will therefore not take place in XML validation. Should discuss other validation steps and where this falls in the workflow, or if we want to use a more strict approach.

**Comment by jungshadow** [comment]
Hi @jennifertlovell! Long-time lurker here given our connection to the project, the NIST CDFs, and the interest in our standards converging. Regarding the latter, this change would be impossible for us to support. VIP's `TimeWithZone` element is based on `xsd:string`, but the NIST CDF elements are based on `xsd:time`. If we wanted to support this, we'd have to weaken the existing typing, which isn't the approach we want to take considering system interoperability. Plus, as you noted, validation could get extremely tricky. Given that, can I ask what the motivation is for this change?
