### ISSUE TITLE
Allow documentation and release notes to be committed with spec changes

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#48]
Currently, there is no way to commit documentation updates and release notes (e.g. by adding to the changelog for a version of the spec) when committing spec changes.  This is mainly because (1) the v5.0 documentation file hasn't been started yet, and (2) there is no place to put the release notes / changelog.

Personally, I'm a fan of doing this stuff when changes are first made so that the documentation isn't pushed out to the very end.  If it's pushed out to the end, it's easy for changes to be missed, etc.  Also, allowing the documentation to be added with the original commit allows the intent to be documented somewhere (as opposed to being scattered throughout the issue thread, the committer's head, and XML comments, etc, and having to be collected later).

**Comment by jungshadow** [comment]
Agree that we should have working documentation (still disagree with changelog) ;) On @pstenbjorn's next update to vip5, I'll merge the documentation changes from master and we can start editing.

**Comment by cjerdonek** [comment]
I thought during the meeting we agreed to do release notes?  (I called it changelog in parentheses.)  My suggestion above was if we could have a way to add to the release notes when the changes are first committed, instead of literally waiting until when there is a release and having to go back and look for changes, etc.

**Comment by jungshadow** [comment]
::sigh:: Ribbing is apparently lost in GitHub comments ;)

**Comment by jungshadow** [comment]
I'm going to close this issue, since we can start hacking on the docs now that they're merged. I'm going to open an issue for discussion, specifically on whether we should have separate docs for the CSV spec. I could go either way.

**Comment by jungshadow** [comment]
The CSV format documentation discussion is #60

**Comment by jungshadow** [comment]
Latest PR #157 should start to completely close this off (and #60 when we get that far with the CSV-side of things). /cc @nomadaisy

**Comment by jungshadow** [comment]
There will be spec additions/modifications and a lot of the docs are still in-progress, but I think we can safely close this issue off, since it is possible to submit updates to both the doc and the changelog now. Reopen if needed.
