### ISSUE TITLE
Restructure repository and delete superfluous files

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/vip-specification#61]
Minimize the number of repository files for subsequent releases. The repository should contain:
* `examples`
* `README.mdown`
* `index.html`
* `vip_spec.xsd`
* `sample_feed.xml`

Delete the following files:
* `sample feed for v2.1.xml`
* `sample feed for v2.2.xml`
* `sample feed for v2.3.xml`
* `sample feed for v3.0.xml`
* `sample_feed_for_v4.0.xml`
* `sample_feed_for_v5.0.xml`
* `spec_v2.2_documentation.html`
* `vip_spec_v2.3_documentation.html`
* `vip_spec_v3.0_documentation.html`
* `vip_spec_pending.xsd`
* `vip_spec_v2.1.xsd`
* `vip_spec_v2.2.xsd`
* `vip_spec_v2.3.xsd`
* `vip_spec_v3.0.xsd`
* `vip_spec_v4.0.xsd`
* `vip_spec_v4.1.xsd`
* `vip_spec_v5.0.xsd`

**Comment by cjerdonek** [comment]
:+1: !

**Comment by pkoms** [comment]
I'm almost completely behind this request, but are you sure you want to kill the 3.0 documentation when it will still be supported by Google?

**Comment by jungshadow** [comment]
@pkoms I'd actually like to make it more accessible. I'm going to post one of my comments on PR #62 here. A few things I didn't outline in my thinking:

1. We tag the current master branch at the latest commit as v3.0 (after a couple of small changes).
    1. This will allow users to easily browse to that point in history.
    2. Additionally, GitHub will archive that commit as a downloadable zip/tar.
    3. We could also tag previous SHAs for other releases (e.g. 2.3, 2.1, etc...), as well.
2. We need to figure out a way to manage our documentation so that the versions are also accessible, not just the current release.
    1. I believe the Open Civic Data folks use Read the Docs, but it would significantly change the way we write/manage our docs.
    2. Jekyll is built into GitHub pages, but I'll need to do a bit more research on how that might help us in this case.

There's been a bit more discussion about it on the PR, but I definitely want to make sure the docs are accessible for the current release and (at least) one previous version.

**Comment by pkoms** [comment]
Thanks for expanding on this -- that's what I get for catching up on email last-first. I'll move my comments to the other PR.

**Comment by jungshadow** [comment]
Closed by #62
