### ISSUE TITLE
XML comments

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#72]
I noticed that a bunch of XML comments that I wrote for the spec in the vip5 branch are no longer present in the latest version of the branch.  Were those intentionally deleted?  The comments were around internationalization (see [here](https://github.com/votinginfoproject/vip-specification/pull/52)).  Are comments discouraged?

**Comment by jungshadow** [comment]
@cjerdonek Hmm...definitely not discouraged, but probably unintentionally destroyed. I'll restore them on the next pull request.
