### ISSUE TITLE
Refactor the XSD so that the attribute ordering is the same as listed in the style guide

### ISSUE THREAD

**Issue by demcg** [votinginfoproject/vip-specification#74]
The attributes in the XSD files should be ordered in the following manner:

1. name
2. type
3. minOccurs
4. maxOccurs

This is a change that will create many small changes all over the file, so it should be merged when there are not too many open branches with major refactors on them.

**Comment by jungshadow** [comment]
This is a great idea and it may be worth capturing now if you're willing to do it, @demcg. I would try to hammer out #75 and #76 at the same time, once we decide those.

@pstenbjorn @jdmgoogle @cjerdonek Sound good to you? If so, let's freeze code changes for a day or two while @demcg is working on this.

**Comment by pstenbjorn** [comment]
@jungshadow yes, this is needed standardization of the xsd.

**Comment by cjerdonek** [comment]
@jungshadow Yes, freezing sounds fine.  My only suggestion is to do each "type" of change as a separate PR to make them easier to review.

By the way, there may be more after this if we think of any (e.g. the ordering of type definitions, both where to put them in the doc and ordering them within).

**Comment by cjerdonek** [comment]
By the way, one thing that should be clarified in the guide is that anything that isn't in the list of four things should go afterwards.  In particular, this would mean that "use" would go after "name" and "type".  (I'm assuming that's how we would want to do it.)

**Comment by demcg** [comment]
I can start this when we hash out #75 and #76

**Comment by demcg** [comment]
@cjerdonek I agree that "use" should be after "type"

**Comment by cjerdonek** [comment]
@demcg I would prefer each issue be done separately so it is easier to review.  Also, that way you can start this one without having to wait.

**Comment by demcg** [comment]
@cjerdonek sounds good, I will start with #74 and get a PR up for it soon

**Comment by demcg** [comment]
@cjerdonek, @jungshadow 
I noticed a small nit to pick about spacing ... should we have a space after the last attribute and before that last angle bracket?

for example:
with space -  ... maxOccurs="1" />
without space - ... maxOccurs="1"/>

We have both patterns, but more than 50% with space

**Comment by cjerdonek** [comment]
@demcg I would say no space.  Something else worth including in the guide.

**Comment by jungshadow** [comment]
@cjerdonek @demcg Again, not to start a flame war, but, since I was raised in the [old school XHTML](http://www.w3.org/TR/xhtml1/#guidelines), I'd rather have that extra visual space after the final attribute.

**Comment by cjerdonek** [comment]
@jungshadow That's fine with me. I don't care too much. :grinning:

**Comment by demcg** [comment]
Sounds good I will make sure that 1 space is between the last attribute and the closing of the tag

**Comment by cjerdonek** [comment]
I created PR #79 to update the style guide per our comments.  The rendered form can be viewed [here](https://github.com/votinginfoproject/vip-specification/blob/feature/issue-74-style-guide/StyleGuide.mdown).

**Comment by demcg** [comment]
link to PR #80
