### ISSUE TITLE
Decide style re: ID attribute names

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#75]
I think the style guide should clarify how to name attributes and elements that correspond to ID's.  The two cases that come to mind are--

1. The ID attribute for a type definition (i.e. a primary key).  1622.2 uses `object_id`, but VIP currently has `id`.  The style guide currently says camelCase, but not what the name should be.  I am okay with following the 1622.2 convention.
2. An ID attribute or element that refers to an ID (e.g. an xs:IDREF).  1622.2 uses names of the form "PartyID", presumably the type name followed by "ID", with camelCase for attributes and TitleCase for elements.  VIP currently uses snake case but follows the same naming convention (e.g. `electoral_district_id`).  The style guide changes this to match VIP, but doesn't say what the name should be.  I would be okay following the 1622.2 convention here as well.

For reference, here is a link to the [latest 1622.2 spec](http://grouper.ieee.org/groups/1622/groups/2/WorkingDocuments/V39/ElectionResultsV39.xsd).

**Comment by demcg** [comment]
@cjerdonek we can add the additional specifier that PKs should be object_id to the attribute section if that is the way the decision goes. @jungshadow, do we want to align the specifier for ID to 1622, or is it better to keep it the way it is (object_id vs. id)?

All of the xs:IDREF relations in the 1622.2 spec are elements, so they follow the TitleCase format.

As for the name I prefer, PartyID if it is an element and partyID if it is an attribute for an xs:IDREF to the Party element.

**Comment by cjerdonek** [comment]
> All of the xs:IDREF relations in the 1622.2 spec are elements, so they follow the TitleCase format.

@demcg Yes, thanks for pointing that out. I'll fix my OP.

**Comment by jungshadow** [comment]
@cjerdonek @demcg I'd prefer to keep `id` rather than change to `object_id` for two reasons:

1. `object_id` is the only attribute in 1622 that doesn't follow their own coding guidelines (i.e. snake_cased rather than camelCased).
2. I never understood the need to change `id` to `object_id`. Both are meant to be unique identifiers, so why use `object_id`?

Other than that, I'm good. @pstenbjorn any thoughts?

**Comment by cjerdonek** [comment]
I will make a PR for this style guide addition (and leave the spec change to @demcg).

**Comment by pstenbjorn** [comment]
@jungshadow the use of xs:ID attributes named `id` is standard and is what is used to identify primary id values in many schemas.  I am not sure why 1622.2 opted for the `object_id` perhaps to avoid ambiguity between the data type and the data type name.  But I would think the continued use of `id` attribute names for primary identifiers would be reasonable.  For further consideration: In the current iteration of VIP the targets of related identifiers (e.g. `electoral_district_id` as an element in `precinct_split`) are standardized as a concatenation of the element name and id.  These would be the xs:IDREF types.

**Comment by cjerdonek** [comment]
> For further consideration: In the current iteration of VIP the targets of related identifiers (e.g. electoral_district_id as an element in precinct_split) are standardized as a concatenation of the element name and id.

@pstenbjorn Yes, this will also be incorporated into the style guide.

**Comment by cjerdonek** [comment]
I created PR #78 for this (for the style guide change, not for the change to the spec).  The rendered form can be viewed [here](https://github.com/votinginfoproject/vip-specification/blob/feature/style-guide-ids/StyleGuide.mdown).

**Comment by cjerdonek** [comment]
Addressed by PR #78.
