### ISSUE TITLE
Update XSD to conform to style guide

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#85]
This issue is to finish updating the schema to match our current style guidelines.  Per [this comment](https://github.com/votinginfoproject/vip-specification/issues/74#issuecomment-89352336), I believe we're still in code freeze while @demcg works on this.  Specifically, attribute and element names need to be updated (which was further clarified by issue #75).

**Comment by demcg** [comment]
@jungshadow @cjerdonek 

I am continuing work on:

### Naming Styles

1. Attributes should be camelCased - The first letter of the second and subsequent words are capitalized.
2. Elements should be TitleCased (PascalCased) - The first letter of every word is capitalized.
3. Enumerations should be spinal-case - all lower case with spaces replaced with hyphens.

I will create a PR later today.

**Comment by jungshadow** [comment]
@demcg How's it coming? Any chance you might have a PR today? If not, just let us know how much longer you need. Also, if you need an additional set of hands, feel free to put up the branch and I can take over.

**Comment by jungshadow** [comment]
Well...that was timely :)

**Comment by demcg** [comment]
@jungshadow @cjerdonek 
I noticed that we have a number of elements that are suffixed by "Url" that are of type xs:string ... should we change these to xs:anyURI?

**Comment by demcg** [comment]
@cjerdonek Can I close this issue?

**Comment by cjerdonek** [comment]
@demcg Yes, I think so.  Thanks!  We can always create a new issue if we see other stuff.
