### ISSUE TITLE
Change file extension from mdown to md

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#96]
I noticed that we are using "mdown" as the file extension for our markdown files, which I have never seen used before.  For example, [Wikipedia](http://en.wikipedia.org/wiki/Markdown) doesn't list it as a possibility on its markdown page.  I wanted to see if we could switch to the more standard "md" (e.g. what GitHub defaults to when auto-creating a README).

**Comment by jungshadow** [comment]
@cjerdonek Agreed. Weird…I could have sworn I used `.md` on the README.

**Comment by cjerdonek** [comment]
Created PR #97 for this.

**Comment by demcg** [comment]
sounds good I followed the extension on the README ... when in Rome and all :-)

**Comment by cjerdonek** [comment]
Great!  I'll go ahead and merge this.  Thanks.
