### ISSUE TITLE
Finish filling out release notes / history doc

### ISSUE THREAD

**Issue by cjerdonek** [votinginfoproject/vip-specification#98]
This issue is for completing the release notes document stubbed out by PR #95.

Per the conference call, post additional items that should be added here, and I can collect them into one or more PR's as more are added.

**Comment by cjerdonek** [comment]
From @jdmgoogle:

> Change: Object identifiers are now of type xs:ID and references are of type xs:IDREF instead of xs:integer; this allows feed creators to perform cursory feed validation before publishing them.

**Comment by jungshadow** [comment]
@jdmgoogle Can we close this?

**Comment by jdmgoogle** [comment]
I believe so, yes. Closing it now.
